DataDog/datadogpy

CONTRIBUTING.md, datadog/__init__.py, datadog/dogstatsd/base.py, setup.py, tests/unit/dogstatsd/test_statsd.py
Forking https://github.com/DataDog/dogstatsd-python/pull/25. 
All credits goes to @benweatherman. Thank you
=> Do not open a socket when DogStatsd is instantiated

datadog/dogshell/event.py
=> fix parameter in event api post

datadog/dogshell/common.py
=> [dogshell] fix wrong default .dogrc :bug:

setup.py
=> [pypi] add classifiers

datadog/api/hosts.py, datadog/dogshell/host.py, tests/integration/api/test_api.py, tests/integration/dogshell/test_dogshell.py
- Also add a test for host muting
=> Update host muting commands

datadog/util/config.py
=> catch any excp when parsing datadg.cnf & fall back

datadog/api/screenboards.py, datadog/dogshell/screenboard.py, tests/integration/api/test_api.py, tests/integration/dogshell/test_dogshell.py
cc @yannmh 
Related to https://github.com/DataDog/documentation/pull/395
=> Add `revoke` method to Screenboard

datadog/api/__init__.py, datadog/api/graphs.py, tests/integration/api/test_api.py
Mostly done, waiting for review
=> [Embed API] Python Wrapper

datadog/dogstatsd/base.py, tests/unit/dogstatsd/test_statsd.py
`use_ms` option to report timed values in milliseconds instead of
seconds (default False).
examples:
```
from statsd import statsd
statsd.use_ms = True
statsd.timed('this.will.use.ms')
def foo():
from statsd import statsd
statsd.timed('this.will.use.seconds')
def foo():
statsd.timed('this.will.use.ms', use_ms=True):
def foo():
```
Fix #10, and inspired by #10, #67 
Thanks @g-- !
=> [statsd] option to time in ms

datadog/__init__.py
fixes https://github.com/DataDog/datadogpy/issues/95
=> clarify the mute param's docstring

datadog/dogshell/wrap.py
**Changes**
* New event body format:
```
>>>> CMD <<<<
>>>> EXIT CODE <<<<
>>>> STDOUT <<<<
>>>> STDERR <<<<
>>>> NOTIFICATIONS <<<<
```
* Trim output to not exceed `MAX_EVENT_BODY_LENGTH` size
* Keep the first 1/3rd of the budget on the top,
and the other 2 thirds on the bottom.
Fix #91
Thanks @gnarf !
=> [dogwrap] new event format + trim output

CHANGELOG.md
=> [changelog] close 0.11.0

CHANGELOG.md
=> [changelog] 0.12.0

BUILD, datadog/threadstats/metrics.py
Based on @leozc's work, supersedes #143.
Thanks again!
=> [threadstats] fix dictionary changed size during iteration

CHANGELOG.md, datadog/dogstatsd/base.py, tests/performance/test_statsd_thread_safety.py
- Cherry-picked https://github.com/DataDog/datadogpy/commit/5c382acfbeae01c43fdedebffa67d578b99da676
- Update `CHANGELOG.md` to 0.6.1
=> Update 0.6.x branch to 0.6.1

CHANGELOG.md
=> [changelog] update v0.14.0

CHANGELOG.md
=> [changelog] v0.16.0

datadog/api/events.py, datadog/api/metadata.py, datadog/api/metrics.py, datadog/api/monitors.py, datadog/api/screenboards.py, datadog/api/service_checks.py, datadog/api/tags.py, datadog/api/users.py
@yannmh please review, thanks!
=> Clarify that API calls returns dictionaries, not JSON strings.

datadog/api/service_checks.py
=> Service check only sends non-null parameters

datadog/dogstatsd/base.py
As currently written, `DogStatsd._report()` can become a bottleneck to high-throughput applications. Profiling against a rough microbenchmark (see below) showed the main time sinks to be `str.join()` and `DogStatsd._report()` itself.
This diff is a little ugly, but dramatically more performant than extending lists and joining strings:
```
(.venv) datadogpy (master)$ python bench.py
Simple: 1000000 metrics in 8.31s (120314.07 metrics/s)
Buffered: 1000000 metrics in 3.87s (258083.36 metrics/s)
(.venv) datadogpy (master)$ git checkout shargan/performance
Switched to branch 'shargan/performance'
(.venv) datadogpy (shargan/performance)$ python bench.py
Simple: 1000000 metrics in 5.32s (187969.19 metrics/s)
Buffered: 1000000 metrics in 1.72s (580796.61 metrics/s)
```
I see similar performance …
=> Speed up DogStatsd._report()

tests/performance/test_statsd_thread_safety.py
Tested under 3.5 and 2.7. Everything in between ought to work as well.
=> Fix tests broken under Python 3

datadog/api/http_client.py
On Python 3, remove `requests` exception contexts before raise a new exception to avoid
accidentally leaking URLs and credentials (API and application keys).
```
Traceback (most recent call last): 
File "/usr/local/lib/python3.6/site-packages/datadog/api/http_client.py", line 73, in request 
result.raise_for_status() 
File "/usr/local/lib/python3.6/site-packages/requests/models.py", line 935, in raise_for_status 
raise HTTPError(http_error_msg, response=self) 
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://app.datadoghq.com/api/v1/downtime?api_key=<redacted>&application_key=<redacted>
During handling of the above exception, another exception occurred:
Traceback (most recent call last): 
[...]
File …
```
=> [http_client] remove `requests` exception contexts

README.md
Minor adjustments to grammar and style (based on our global conventions and style guide).
cc @l0k0ms
=> [docs] grammar and style fixes in README

tests/unit/api/helper.py
Fix unit tests after https://github.com/DataDog/datadogpy/pull/272
=> [tests] fix requests mock

setup.py
#277 @yannmh fixed the issue mentioned in issue 277 https://pypi.org/project/vaddipar/ Here is the same project uploaded to pypi under my name for verification purposes. Please take a look at the project vaddipar on pypi and if the issue is fixed I will delete the project.
=> Fixed issue 277 of no description in pypi

datadog/dogshell/event.py
Fix syntax errors from https://github.com/DataDog/datadogpy/pull/287
Thanks again @gplasky
=> Cast date_happened to an integer to match API spec

.travis.yml, setup.py, tox.ini
=> Support Python 3.7, drop 3.3

doc/source/conf.py
Example: http://docs.python-requests.org
=> Change docs theme to Alabaster

README.md
Customer was confused about how to add tags and set namespaces. 
Adding example to repo.
=> Adding note about setting namespace, tags

datadog/api/exceptions.py, datadog/api/http_client.py
Handle http code 429 rate limiting in external python library
=> Handle http code 429 for rate limiting

datadog/api/api_client.py, datadog/api/dashboard_list_v2.py, datadog/api/dashboard_lists.py, datadog/api/resources.py, datadog/dogshell/dashboard_list.py
- Add `DashboardList.v2.get_items`, `DashboardList.v2.add_items`, `DashboardList.v2.update_items` and `DashboardList.v2.delete_items` API calls
=> [dashboards] Add support for dashboard list API v2

datadog/threadstats/metrics.py
As described in #142, the MetricsAggregator is not threadsafe under Python 3. This is a regression caused by a change in how the `.keys()` method works under Python 2 vs Python 3: in Python 3, calling `.keys()` returns a view rather than a copy of a list.
The solution here is to use a reentry lock around the modifiers and accesses to `self._metrics`, in order to ensure that any concurrent calls to `MetricsAggregator.flush()` and `MetricsAggregator.add_point()` have no race conditions.
Note that the stack trace which this changeset fixes is:
```
RuntimeError: dictionary changed size during iteration
File "datadog/threadstats/base.py", line 307, in flush
metrics, dists = self._get_aggregate_metrics_and_dists(timestamp or time())
File "datadog/threadstats/base.py", line 348, in …
```
=> fix(threadstats): ensure MetricsAggregator is threadsafe

datadog/dogshell/monitor.py
Modified datadogpy/datadog/dogshell/monitor.py:
- Added --tags to post_parser.add_argument
- Added tag ingestion via args.tags to _post method 
- Added tags to _post method res object
=> Update to dogshell monitor _post method - tag ingestion

datadog/dogshell/__init__.py
Based on @sc68cal's PR #344 and supersedes it. Thanks @sc68cal.
Fixes #255
=> Add documentation for environment variables

CHANGELOG.md, setup.py
=> Prep 0.29.1 release

CHANGELOG.md, setup.py
=> Prep Release 0.29.2

datadog/dogshell/screenboard.py, datadog/dogshell/timeboard.py, setup.py, tests/integration/api/test_api.py, tests/integration/dogshell/test_dogshell.py, tests/unit/api/helper.py, tests/unit/api/test_api.py, tests/util/contextmanagers.py, tox.ini
This PR does the following:
* Adds __init__ files to the integration test folders
**The integrations tests weren't being run previously due to there not being any __init__ files in the integration/performance/dogshell folders so the test framework couldn't load the tests - https://docs.python.org/3/library/unittest.html#unittest-test-discovery
* Fixes the loading of environment variables and overall setUp/tearDown logic of these tests
* Copies the EnvVars class from datadog_checks_dev so we have a context manager for safely manipulating environment variables. 
* Fixes the integration tests that were broken, various fixes based on what the API returns/and logic issues within the tests
* Dogshell tests are also fixed up and should pass
Note: We aren't actually running these integration …
=> Fixes Integration Tests and fix dogshell screenboard creation

datadog/api/comments.py, datadog/api/events.py, datadog/dogshell/comment.py
Removed functionality and DeletableAPIResource (for public doc) as they're no longer supported
Related to: https://github.com/DataDog/documentation/pull/5033
=> removed delete comment and DeletableAPIResource 

CONTRIBUTING.md
Add an example to the CONTRIBUTING.md file for adding a new endpoint to this project. 
Also adds a quick note about how to editable install this project. Useful for running quick manual tests.
=> Add section to contributing.md about adding new endpoints

.gitignore, setup.py, tests/integration/api/test_api.py, tests/integration/dogshell/test_dogshell.py, tests/integration/util/snapshot_test_utils.py, tests/performance/test_lambda_wrapper_thread_safety.py, tests/performance/test_threadstats_thread_safety.py, tests/unit/dogstatsd/test_statsd.py, tests/unit/threadstats/test_threadstats.py, tox.ini
Nose is not maintained for a few years now; it's not a really good idea to
stick to it at this point.
Uses pytest instead to run tests.
=> Replace nose by pytest

datadog/api/users.py
Let's keep using v1 with the singular. We'll move to plural with v2
=> Revert "[users] Updated users resource name to match new plural endpoints"

README.md, tests/integration/api/test_api.py, tests/integration/dogshell/test_dogshell.py, tox.ini
also fixes one bug with the api tests
=> Rework dogshell integration tests

tests/integration/api/test_api.py
The direct response of the API isn't consistent. So let's just do the create and update, then verify the success by getting the tags after waiting for them to get updated
=> Fix flakyness of test_tags

.azure-pipelines/integration_tests.yml, tests/integration/api/test_api.py, tests/unit/api/test_api.py, tox.ini
also fixes a bunch of flakyness
=> Test user not admin anymore, can't update other user

.azure-pipelines/unit_tests.yml
Change the display name of the azure pipeline job to be the TOKENV being run
=> Make flake8 its own CI job

datadog/api/metrics.py
Addresses https://github.com/DataDog/datadogpy/issues/269.
=> Clarify docstring for metrics

CHANGELOG.md, setup.py
Create the 0.32.0 release that includes support for synthetics and the fix for distribution metrics.
=> Start 0.32.0 release

.github/CODEOWNERS, README.md
This PR updates the main readme.md file in order to properly reflect the main functionalities of this DogStatsD lib.
It also adds Datadog documentation team as a code owner over Markdown files in order to smooth further doc improvement + insuring better sync between public doc and the functionalities of Datadog-py
=> Refactoring doc to better reflect DogStatsD funct

datadog/api/api_client.py, datadog/api/monitors.py, datadog/dogshell/monitor.py, datadog/dogshell/service_level_objective.py, tests/integration/api/constants.py, tests/integration/api/test_api.py, tests/integration/dogshell/test_dogshell.py
=> [MA-557] Add support for new `Monitor.can_delete` endpoint.

datadog/dogshell/wrap.py
As `dogwrap` does not currently have an option to choose the site.
=> Add EU endpoint

datadog/dogshell/wrap.py
=> [dogwrap] Add duration as metric

CONTRIBUTING.md
Add extra labels to doc
See changes
Manual / review
=> Updating Contributing doc

.github/CODEOWNERS, .github/labeler.yml
=> Add codeowners per subproject

LICENSE-3rdparty.csv, RELEASING.md
Add 2rd party file
manual review
=> Add 3rd party licenses file and update doc

RELEASING.md, setup.py
Fix syntax of setup.py, and update releasing.md
=> Fix setup.py syntax for console scripts

RELEASING.md, setup.py
Start development cycle for 0.35.0
=> Start new dev cycle

CHANGELOG.md, setup.py
=> Release 0.34.1

setup.py
=> start new release cycle

datadog/__init__.py
looks off in readthedocs https://datadogpy.readthedocs.io/en/latest/#datadog-api-module
https://a.cl.ly/Qwu77GkL
indenting some parameter descriptions
=> modifying indent

CHANGELOG.md, setup.py
=> Release 0.35.0

tests/integration/dogshell/test_dogshell.py
Fixes problem with Click 7.1.1 that removed unused param.
=> tests: remove unused mix_stderr param

tests/unit/dogstatsd/test_statsd.py
Fix the tests for broken socket and overflown socket, that were not effectively testing anything since the `send_to_server` method has a catchall clause, which would never make the test fail.
Mock `log` and assert we entered the proper catch statements
=> Fix test for socket error

README.md
based on [instantiation](https://github.com/DataDog/datadogpy/blob/f6e020fe9d7554d751b0ce1c73c19124e3ea54fe/datadog/__init__.py#L102), clarify how to instantiate dogstatsd for UDS
=> [Documentation Update] Add UDS Configuration

datadog/dogshell/wrap.py
Fix help output of `dogwrap`, since `--site` is case sensitive
Change case of `EU` and `US` in the help output
=> Fix dogwrap help output case

CHANGELOG.md, DEVELOPMENT.md, setup.py
=> Release v0.36.0

setup.py
=> Bump v0.37.0.dev

.github/PULL_REQUEST_TEMPLATE.md
Fixes a typo and a link in PR template
Current link leads to [https://github.com/about/careers#pull-request-title](/CONTRIBUTING.md#pull-request-title), changed the link to [absolute](https://github.com/DataDog/datadogpy/blob/master/CONTRIBUTING.md#pull-request-title).
=> Fix link to CONTRIBUTING.md#"Pull request title"

.github/labeler.yml
Updates `labeler.yaml` to fix auto-labeling action for `*.md` files in the root directory.
Current rule does not cover `/readme.md` and causes #591 to fail.
Adds an additional rule for the root directory.
Checked the rule on https://globster.xyz/
Does not affect end-users, only …
=> Label changes to `*.md` in the root directory

README.md
Add missing import for `initialize`
Improves documentation for Python/DataDog beginners
Adds the exact import statement one need to make the example code work
n/a
n/a
I verified the example code in my project
nope
No changes to any code, only docs
=> Update DogStatsD example in README.md

doc/requirements.txt, doc/source/conf.py
This updates the sphinx theme to something a bit more readable.
=> Use RTD theme for doc site

datadog/api/synthetics.py
Small docstring fix
Closes #612
=> Fix synthetics create_test docstring

datadog/util/hostname.py
=> Turn warning into info

datadog/threadstats/base.py, tests/unit/threadstats/test_threadstats.py
Duplicate logic from #548 in threadstats.
Closes #618
=> Support DD env vars in threadstats

tests/integration/dogshell/test_dogshell.py
Increases the wait time for retries for dogshell tests accounting for delayed results
=> Increase dogshell test retry wait time

setup.py
=> Fix dependency for Python 2.7

tests/performance/test_statsd_thread_safety.py
Fixes `performance/test_statsd_thread_safety.py` test
These test have been broken for a while since they mocked a changed
component name but the fix was simple to re-enable it.
Closes https://github.com/DataDog/datadogpy/issues/658
Test's internal objects now point to the correct ones in statsd
`python2 -m unittest -vvv tests.performance.test_statsd_thread_safety`
- [] PR title must be written as a CHANGELOG entry [(see why)](https://github.com/DataDog/datadogpy/blob/master/CONTRIBUTING.md#pull-request-title)
=> [tests] Fix DSD thread safety benchmark tests

tests/unit/dogstatsd/test_statsd.py
Adds tests for `statsd` default and custom max packet sizes
The functionality of packet size configuration is already working but was lacking functional
tests. This change ensures that both the UDS and UDP max packet sizes
are correctly defaulted as well as any overrides via the `max_buffer_len` parameter.
N/A
N/A
N/A - tests are verifying the functionality
N/A
N/A
=> [tests] Add tests for `statsd` default and custom max packet sizes

doc/source/index.rst
Updates some of the documentation that ends up on https://datadogpy.readthedocs.io/en/latest/
Looks like we haven't updated the docs that end up at the site
https://datadogpy.readthedocs.io/en/latest/. This PR ensures that at
least some of the information is now up to date, including the special
caveats about the new `datadog.dogstatsd` behavior.
N/A
N/A
N/A
=> [docs] Update documentation that is out of date

doc/source/index.rst
The current provided example for the initialize() method: a) doesn't work, and b) does not conform to the method signature described immediately afterward. The suggested change yields a functional example and is conformant.
This PR provides a fix for a broken example.
The change …
=> Make the initialize() example match its method signature

README.md
=> Add a note pointing to datadog-api-client

datadog/dogshell/__init__.py, datadog/dogshell/common.py, datadog/dogshell/wrap.py
=> Add AP1 Datacenter

datadog/dogstatsd/base.py, datadog/dogstatsd/container.py, tests/unit/dogstatsd/test_container.py, tests/unit/dogstatsd/test_statsd.py
=> feat(origin detection): implement new spec
