DataDog/datadogpy

- datadog/__init__.py
- tests/unit/api/test_api.py
Allows users to set their API and application keys via `DATADOG_API_KEY ` and `DATADOG_APP_KEY ` like we do for the API host with `DATADOG_HOST `.
Fix https://github.com/DataDog/dogapi/issues/133
> [core] API parameters from environment variables

- datadog/dogshell/wrap.py
Fix #18
I don' feel confortable about auto-selecting a priority based on the output (i.e. `SUCCESS` -> `low` and `ERROR` -> 'normal'.)
cc @miketheman
> [dogwrap] add priority option

- datadog/dogshell/wrap.py
- By default, dogwrap now forwards the stdout and stderr of the command
it executes to the terminal launching dogwrap.
- This behaviour can be prevented using the --buffer_outs option
(dogwrap then acts just as it used to do)
- I also added some comments in the code.
- Finally, I added help messages for the different possible options, as
well as an "USAGE" description and and version number (automatically
enabled --version option for dogwrap).
> [stdout stream] Added an option to stream outputs

- datadog/util/config.py
Fix #47. Thanks a lot @apoorvab !
> fix #47 py34 windows initialization issue

- datadog/api/base.py
- datadog/api/graphs.py
- datadog/api/metrics.py
- tests/integration/api/test_api.py
- tests/unit/api/helper.py
- tests/unit/api/test_api.py
* Add support for metric query API
* Allows to re-set `_timeout` parameter dynamically
> metric query API support

- datadog/dogstatsd/base.py
- tests/performance/test_statsd_thread_safety.py
Fix #57. Thanks @GrahamDumpleton !
> [statsd] fix socket creation thread safeness

- setup.py
Versions prior to 2.6.0 are vulnerable to a specific session hijack
attack. While we do not use cookies when interacting with the Datadog
API, it is good practice to keep up with security patches like this.
More info: http://www.openwall.com/lists/oss-security/2015/03/14/4
> update requests library, per CVE-2015-2296

- datadog/api/metrics.py
API documentation was illegitimately promoting usage of `metric_type`
parameter instead of `type`.
To be consistent and avoid 'backward incompatibilities', properly rename
this parameter.
> 'metric_type' should be 'type'

- datadog/dogstatsd/base.py
- tests/unit/dogstatsd/test_statsd.py
This enables a context manager in statsd so you can easily time a set of code without saving the start time, etc. manually:
```python
with statsd.timed_context('user.query.time', sample_rate=0.5):
pass
start = time.time()
try:
get_user(user_id)
finally:
statsd.timing('user.query.time', time.time() - start)
```
Two tests are also added for this code.
Fixes #25
Please let me know if you want anything changed, etc. I'd love to see this in the next release!
> Add a timed context manager to statsd.

- datadog/api/base.py
- datadog/api/monitors.py
- datadog/dogshell/monitor.py
- tests/integration/api/test_api.py
- tests/integration/dogshell/test_dogshell.py
- Adjust dogshell descriptions to distinguish between mute_all/unmute_all and mute/unmute
- Add new monitor unmute arg (`all_scopes`) to allow clearing all mute settings for a given monitor
- Update monitor mute tests
- Include additional information in 403 response exceptions
> Clarify monitor muting endpoints

- tox.ini
'mock' version 1.0.1 is the last version compatible with Python 2.6.
> [test] force mock to version 1.0.1 for py26 compat

- datadog/dogstatsd/base.py
- tests/unit/dogstatsd/test_statsd.py
I have added a optional param (constant_tags) to the Dogstatsd client to append tags to every metrics call.
Useful for setting project wide tags like version.
> new constant tags for statsd client

- datadog/dogstatsd/base.py
- tests/unit/dogstatsd/test_statsd.py
If the metric is *NOT* provided, it defaults to the function's module and name.
I find this convenient to wrap some functions where the metric is simply going to be the name of the function, in particular to wrap celery tasks.
I discussed this briefly with @remh on IRC and he suggested I put up a PR and we can discuss it.
> Make the metric optional for the timed decorator.

- datadog/__init__.py
- datadog/api/__init__.py
- datadog/api/base.py
In my production environment the server was missing root certificates to verify datadogs SSL cert which made the datadog api to fail with a No such file or directory error.
Added the option to use the verify parameter in requests to configure a ca certificates file or to disable verification.
> Add option for SSL verification with Requests library

- datadog/__init__.py
- datadog/api/__init__.py
- datadog/api/base.py
- tests/unit/api/helper.py
- tests/unit/api/test_api.py
Datadog API HTTP client raises ApiError (400, 403 or 404 status codes)
and HTTPError (others) exceptions for bad requests.
BUT, we are, by default, muting any exceptions before they escape from
the library. This makes difficult to catch errors and interact with the
API.
These changes introduces a `mute` option settable from `initialize`
method, to select the desired behavior.
Fix #74
> [api] option to unmute ApiError exceptions

- datadog/api/base.py
- datadog/dogshell/__init__.py
- datadog/dogshell/comment.py
- datadog/dogshell/common.py
- datadog/dogshell/downtime.py
- datadog/dogshell/event.py
- datadog/dogshell/host.py
- datadog/dogshell/metric.py
- datadog/dogshell/monitor.py
- datadog/dogshell/screenboard.py
- datadog/dogshell/search.py
- datadog/dogshell/service_check.py
- datadog/dogshell/tag.py
- datadog/dogshell/timeboard.py
- datadog/dogshell/wrap.py
- datadog/util/compat.py
- datadog/util/hostname.py
- setup.py
- tests/unit/api/helper.py
`simplejson==3.0.0` introduced Python > 3.3 support. Use it instead of falling back with stdlib `json` package.
> [deps] use `simplejson` with Python 3.x

- CHANGELOG.md
- setup.py
* [FEATURE] Option to time in ms with `statsd`, [#78][] (thanks [@g--][])
* [FEATURE] Option to unmute `api` ApiError exceptions, [#76][]
* [OTHER] Use `simplejson` with Python 3.x, [#83][]
[#76]: https://github.com/DataDog/datadogpy/issues/76
[#78]: https://github.com/DataDog/datadogpy/issues/78
[#83]: https://github.com/DataDog/datadogpy/issues/83
[@g--]: https://github.com/g--
> Update to v0.9.0

- datadog/dogshell/wrap.py
Usage:
`dogwrap -n test-job -k $API_KEY --tags "test, cron, test2" --submit_mode all "ls -lah"`
> add tag support to dogwrap

- datadog/dogstatsd/base.py
- datadog/threadstats/base.py
- tests/unit/dogstatsd/test_statsd.py
- tests/unit/threadstats/test_threadstats.py
Added the same constant_tags to the ThreadStats class as I had done to the blocking version.
> Adds constant_tags to ThreadStats

- datadog/api/base.py
- datadog/api/users.py
- doc/source/index.rst
- tests/integration/api/test_api.py
Additional changes:
- Add a deprecation message to `invite` method of `api/users`
- 409 HTTP error codes are now recognized as ApiError exceptions
> [api] Add user CRUD

- datadog/dogstatsd/base.py
- tests/unit/dogstatsd/test_statsd.py
When previously-defined metric-level tags (non-literal list) are passed into the `gauge()` function,
the metric-level tag list will be modified if `constant_tags` is not `None`. This is due
to the `+=` operator modifying the metric-level list by appending
the list `constant_tags`.
If you're using dogstatsd to send your metrics, this will inevitably lead to a `error: [Errno 90] Message too long` since the UDP packet size has an upper limit.
For an example of this, see the new test, `test_gauge_constant_tags_with_metric_level_tags_twice`.
Use the following instead of `+=`:
```python
tags += self.constant_tags
tags = tags + self.constant_tags
```
> Fix bug where tags list increases in size

- datadog/api/metrics.py
- tests/unit/api/test_api.py
`Metric` API supports built-in real numerical data types.
> [api] `Metrics`: support long` data type

- datadog/api/metrics.py
- tests/unit/api/test_api.py
Extends `Metrics` data type support to any real number.
> [api] `Metrics`: support real numerical data types

- datadog/__init__.py
- datadog/dogstatsd/__init__.py
Add a top-level import for DogStatsd, i.e.
```python
from datadog import DogStatsd
```
is equivalent to
```python
from datadog.dogstatsd.base import DogStatsd
```
> [dogstatsd] add a top-level import for DogStatsd

- datadog/api/events.py
As far as I can tell, you've forgot to document the parameter `alert_type` in `Event.create`. I guess there should also be a test for this, but I wasn't sure how to go about this.
> Document parameter alert_type in Event.create

- datadog/threadstats/base.py
Do not modify metric-level `tags` parameters when `constant_tags` is
set.
Similar to #94.
> [threadstats] do not modify metric/event-level tags

- datadog/dogstatsd/base.py
- datadog/threadstats/base.py
- tests/unit/dogstatsd/test_statsd.py
- tests/unit/threadstats/test_threadstats.py
- tests/util/contextmanagers.py
creates an additional technique for adding tags to all metrics by defining a comma separated list of tags in the `DOGSTATSD_TAGS` environment variable.
use case:
currently we add a plethora of global tags by adding them to our dd-agent configuration on each node. as we progress towards using container technologies, it would be swell if we could seamlessly inject some of these tags on a container by container basis (app name, version, build) rather than adding them to the dd-agent which will be configured with tags for instance id, region, availability-zone etc.
> attach additional tags as defined in DOGSTATSD_TAGS environment variable

- datadog/dogshell/event.py
Allow user to pass `alert_type` arg to `dog event post` command.
> support alert_type arg for dog event post

- datadog/dogstatsd/base.py
- datadog/threadstats/base.py
- tests/unit/dogstatsd/test_statsd.py
- tests/unit/threadstats/test_threadstats.py
Add a `namespace` parameter to `threadstats` to automatically prefix all metric names.
Fix #113.
> [dogstatsd][threadstats] namespace support 

- datadog/dogstatsd/base.py
- tests/unit/dogstatsd/test_statsd.py
If you do, you'll get errors like this in `/var/log/messages`:
```
Metric value must be a number: metric.name, None
```
> don't send None to statsd daemon as metric value

- datadog/api/base.py
- datadog/dogshell/common.py
- datadog/dogshell/event.py
- datadog/dogshell/metric.py
**[dogshell] add hostname by default to event posts**
By default, `dogshell` event posts (`dog event post` command) are now
automatically associated with the local host.
The `--host` and `--no-host` (new) options allow to override this value
with a given host, or no host.
```python
dog event post "title" "content"
dog event post --host "foo.bar" "title" "content"
dog event post --no-host "title" "content"
```
**[dogshell] add hostname by default to metric posts**
By default, `dogshell` event posts (`dog metric post` command) are now
automatically associated with the local host.
The `--host` and `--no-host` (new) options allow to override this value
with a given host, or no host.
The `--localhostname` option is deprecated, as made default when no
`--host` is set.
```python
dog metric post …
```
> [dogshell] add hostname by default to event/metric posts

- datadog/dogshell/__init__.py
- datadog/dogshell/comment.py
- datadog/dogshell/downtime.py
- datadog/dogshell/event.py
- datadog/dogshell/host.py
- datadog/dogshell/metric.py
- datadog/dogshell/monitor.py
- datadog/dogshell/screenboard.py
- datadog/dogshell/search.py
- datadog/dogshell/service_check.py
- datadog/dogshell/tag.py
- datadog/dogshell/timeboard.py
- datadog/util/hostname.py
**[dogshell][py3] print usage when no argument**
In accordance with the behavior on Python 2.x, `dog` command with
Python 3.x should print the usage when no subparser is specified.
Instead, the uncalled code block is executed and raises:
```
AttributeError: 'Namespace' object has no attribute 'func'
```
Fix it and print usage.
More information: http://bugs.python.org/issue16308
Fix #85
**[py3] better compatibility**
Improve compatibility with Python 3.x.
> [dogshell][py3] print usage when no argument

- datadog/dogstatsd/base.py
- tests/performance/test_statsd_thread_safety.py
- tests/unit/dogstatsd/test_statsd.py
**[dogstatsd][test] rewrite thread safety tests**
Rewrite DogStatsd thread safety tests.
**[dogstatsd] fix thread-safety of @timed decorator**
Rebase of #112.
> When using @timed as a decorator, it's not thread-safe to call itself as a context manager. The decorator creates one instance of this class, and since the context manager stores the start time on the instance, calling it again in parallel will overwrite the start time of the earlier call.
So, for the decorator version, the start time needs to be kept in the call
stack.
This includes a test case which demonstrates the problem.
Rebased to move tests to `tests/unit/dogstatsd/test_statsd.py`
Thanks again @mgood !
> [dogstatsd] fix thread-safety of @timed decorator

- datadog/__init__.py
- datadog/dogstatsd/base.py
- tests/unit/dogstatsd/test_statsd.py
When you run in a containerized environment, the dogstatsd server will
likely expose its port on the host network. If you have an application
that runs within a container, it needs to connect to it using the
default route.
> [dogstatsd] Allow to dynamically use default route as a statsd host

- datadog/api/events.py
We're adding a delete endpoint for events in the app, so this PR makes `Event`s `Deletable`.
> [api] events are deletable

- .travis.yml
- tox.ini
Set Travis CI and Tox to test with Python 3.5.
Fix #148.
> [ci] test with python 3.5 ✅

- datadog/dogstatsd/base.py
- tests/unit/dogstatsd/test_statsd.py
Have `_TimedContextManagerDecorator` return `self` from `__enter__` so that it can be modified within the block. e.g.
```Python
with timed('foo.bar', tags=['key:val']) as timer:
if blip:
timer.tags.append('result:blip')
```
This can be worked around by assigning timed's result to a var and then doing a `with timer`, but this is much cleaner and shouldn't result in any backwards compatibility issues.
> _TimedContextManagerDecorator enter -> self

- datadog/dogstatsd/base.py
- datadog/util/compat.py
- tests/unit/dogstatsd/test_statsd.py
Using unicode with DogStatsD tags causes `UnicodeDecodeError`
exceptions.
Do not raise on unicode tags. Fix #132.
> [dogstatsd] support unicode tags 🔣

- datadog/dogstatsd/base.py
- tests/unit/dogstatsd/test_statsd.py
> Provide elapsed time from _TimedContextManagerDecorator

- datadog/dogstatsd/base.py
- tests/unit/dogstatsd/test_statsd.py
Added support for manually starting and stopping a timer.
Now it can be used something like this:
```python
@app.before_request
def before():
request.page_load_timer = statsd.timed('metric')
request.page_load_timer.start()
@app.after_request
def after():
request.page_load_timer.stop()
```
> Allow starting and stopping timed() manually

- datadog/api/events.py
Fix https://github.com/DataDog/datadogpy/issues/158
> [doc] fix link to event api documentation

- .gitignore
- datadog/dogstatsd/base.py
- datadog/dogstatsd/base3.py
- datadog/dogstatsd/context.py
- datadog/dogstatsd/context_async.py
- datadog/util/compat.py
- tests/unit/dogstatsd/test_statsd.py
Rebase of #146.
**Additional changes:**
* Move Python 3.5+ evaluation methods to `datadog.util.compat` module
* Move `TimedContextManager` to `datadog.dogstatsd.context` module
* Quarantine `TimedContextManager` coroutine decorator in
`datadog.dogstatsd.context_async`
* Unit test coverage to assert DogStatsd compatibility with coroutine
functions
Thanks a lot of @thehesiod 🙇
> [dogstatsd] `timed` support for coroutine functions

- datadog/__init__.py
- datadog/api/api_client.py
- datadog/api/http_client.py
- datadog/api/resources.py
- datadog/dogshell/__init__.py
- datadog/dogshell/common.py
- datadog/dogstatsd/base.py
- datadog/threadstats/base.py
- datadog/util/config.py
- datadog/util/hostname.py
Split `dd.datadogpy` logger to one per module, i.e.
* `datadog.api`
* `datadog.dogstatsd`
* `datadog.threadstats`
Setup the `NullHandler` handler by default as advised in
https://docs.python.org/3/howto/logging.html#configuring-logging-for-a-library
> [logging] rename loggers and set handlers to null

- CHANGELOG.md
- datadog/__init__.py
- datadog/api/api_client.py
- datadog/dogstatsd/base.py
- datadog/dogstatsd/route.py
- datadog/util/compat.py
- tests/unit/dogstatsd/fixtures.py
- tests/unit/dogstatsd/fixtures/route
- tests/unit/dogstatsd/test_statsd.py
DogStatsd fails resolving the system's default route in the following
scenarios:
* no proc filesystem
* no default gateway found in `/proc/net/route`
Raise user intelligible exceptions in those cases.
Fix https://github.com/DataDog/datadogpy/issues/156
> [dogstatsd] better exceptions on route resolution

- datadog/api/http_client.py
The documentation at the following URL states: "Explicitly set
follow_redirects=False when calling Urlfetch, as it avoids a heavier-weight
service designed to follow redirects." I have not been able to measure any
significant difference, but since the Datadog API doesn't use redirects,
this should be a safe change. Source:
https://cloud.google.com/appengine/docs/python/microservice-performance#use_the_shortest_route
We will be using this in production at Bluecore very shortly. Happy to abandon this or sign a CLA or whatever you might want me to do. Thanks!
> [api] set follow_redirects=False on App Engine; recommended in docs

- datadog/dogstatsd/base.py
- tests/unit/dogstatsd/test_statsd.py
Our unittests have been printing out warnings for awhile since we're unable to close the socket after it's nulled out.  This ensures the socket is closed if it was opened.
> fix socket "leak"

- datadog/threadstats/base.py
By default, histogram sends a more limited set of metrics than the documetation claims.
> Correct docstring for histogram

- datadog/api/__init__.py
We have  1000+ monitors in our setup, and often hit the 3 default timeout of 3 seconds when poking around using datadog/api.
This bumps the default setting to 60 seconds, which allows us to retrieve our monitors. I do realise  bumping the default value is not the most subtle approach, but as 3 seconds is pretty short -much shorter than any CLI http client I've seen, and considering the REST response times for larger customers are often over 3 seconds this could be good enough.
> Bump default timeout from 3 to 60 seconds.

- datadog/threadstats/base.py
Fixed a few minor typos in the documentation:
* A newline which wasn't rendering the code example.
* `They most recent value` instead of `The most recent value`.
> Fixed some documentation typos.

- datadog/api/__init__.py
- datadog/api/metadata.py
- datadog/dogshell/__init__.py
- datadog/dogshell/event.py
- datadog/dogshell/wrap.py
- Adds GET and PUT operations for the metadata endpoint.
- Some confusion around https://github.com/DataDog/datadogpy/compare/agrant/metrics_metadata?expand=1#diff-0741b06f081c976a404268a44c97cc2fR15 and if this should be `metrics` or `metadata` ?
> Add metric metadata endpoints

- datadog/api/events.py
Datadog Event API documentation specifies `aggregation_key`: https://docs.datadoghq.com/api/#events. I also tested and it works.
> Add aggregation_key to events documentation

- datadog/api/monitors.py
- datadog/dogshell/monitor.py
Add the different available options to filter monitors to the `dog
monitor show_all` command.
Also update the PyDoc to document the different parameters according to
http://docs.datadoghq.com/api/.
> [dogshell] filter options to monitor command

- datadog/dogshell/wrap.py
Fixes encoding issue in non-specific `sys.stdout.encoding=None` environment. See #201
> Encode from unicode before writing to stdout, stderr.

- CHANGELOG.md
- datadog/dogstatsd/base.py
dogstatsd6 will allow custom metrics to be sent via a datagram unix socket instead of UDP (see https://github.com/DataDog/datadog-agent/pull/252). This PR add a use_unix_socket option to the DogstatsD object in order to allow using this communication channel.
Containers make it harder to reach the dogstatsd server from client applications and we don't have a future-proof network solution that could work across all orchestrators. This allows to bypass the network stack altogether and use a host-local protocol. See https://github.com/DataDog/docker-dd-agent/issues/195 for more context.
As unix datagram and UDP share the same semantics, the patch is pretty small and unobstrusive.
Socket connection is set to non blocking: if the server is unresponsive, the packets are dropped, mirroring what …
> add socket_path option to enable unix socket traffic to dogstatsd6

- datadog/api/events.py
Fix the documentation. When creating an event, the associated `host`
must be a string, not a list.
> [api] event's `host` must be a string, not a list

- datadog/api/metrics.py
Adding support to the SDK for listing active metrics
> Add list metrics to datadog.api.metrics

- datadog/api/screenboards.py
The http-method of the share of the Screenboard API changed from GET to POST and it stopped working, I fixed it.
> change http-method GET to POST on api.Screenboard#share

- .travis.yml
Fix flake8's version to 3.4.1.
flake8 3.5.0 makes failure to current datadogpy's code base.
(The failure of #234 is the same reason)
```
$ flake8 --max-line-length=100 datadog
datadog/dogshell/monitor.py:100:13: E722 do not use bare except'
datadog/dogshell/monitor.py:119:13: E722 do not use bare except'
datadog/dogshell/screenboard.py:177:9: E722 do not use bare except'
datadog/dogshell/screenboard.py:198:9: E722 do not use bare except'
datadog/dogshell/screenboard.py:274:9: E722 do not use bare except'
datadog/dogshell/timeboard.py:144:9: E722 do not use bare except'
datadog/dogshell/timeboard.py:235:9: E722 do not use bare except'
datadog/dogshell/timeboard.py:255:9: E722 do not use bare except'
datadog/threadstats/base.py:305:9: E722 do not use bare except' …
```
> fix flake8 version to 3.4.1

- datadog/api/service_checks.py
- tests/unit/api/test_api.py
https://github.com/DataDog/datadogpy/issues/206#issuecomment-343512407 introduced a basic python3 error where we attempted to iterate over a dictionary we were modifying, yielding an exception.
We didn't have any unit tests around this so I added one. This fixes both the actual call that I was making and provides a regression test.
I'm happy to clean up the commits once I get basic validation that this is the right direction.
If it's more important than I realize to actually filter out the `None` params, we'll need to change the way that we do that (iterating over `keys` and building up a new dictionary with the appropriate key/value pairs.
> Fix ServiceCheck none parameters for calls from dogshell, etc on python3.

- datadog/dogshell/wrap.py
Wrapping a command with python3 is broken due to string changes in python3. This decodes the string using the `_fwd_out` encoding. 
Another option is to just use the `utf-8` decoded line below for both.
```
Exception in thread Thread-1:
Traceback (most recent call last):
File "/usr/local/lib/python3.6/threading.py", line 916, in _bootstrap_inner
self.run()
File "/dbt/src/datadog/datadog/dogshell/wrap.py", line 68, in run
self._fwd_out.write(line)
TypeError: write() argument must be str, not bytes
```
> dogwrap python3 string changes

- datadog/dogstatsd/base.py
Adds support to datadogpy for sending global distribution values via dogstatsd.
This is a beta feature. 
I did not add support to the threadstats package because it doesn't seem to make sense - no local aggregation should be done on these.
> Add beta support for sending global distribution metrics via dogstatsd

- datadog/threadstats/base.py
- datadog/threadstats/metrics.py
- tests/unit/threadstats/test_threadstats.py
On exit, flush all metrics regardless of the rollup intervals.
> [threadstats] flush all metrics on exit

- datadog/threadstats/base.py
- datadog/threadstats/constants.py
- datadog/threadstats/metrics.py
- tests/unit/threadstats/test_threadstats.py
**Problem**
At present in ThreadStats various types of metric gets created like gauge, count, histogram, etc. but at the time of flushing for each metric type is set to "gauge". This is a problem as sending count from server becomes gauge in the web. Changing the type in web will not have any effect as from the server it is always coming as gauge.
**Solution**
Assign the right metric type based on the metric functionality.
> ThreadStats - Send correct metric type instead of always sending Gauge

- datadog/api/__init__.py
- datadog/api/comments.py
- datadog/api/dashboard_lists.py
- datadog/api/downtimes.py
- datadog/api/events.py
- datadog/api/graphs.py
- datadog/api/hosts.py
- datadog/api/infrastructure.py
- datadog/api/metadata.py
- datadog/api/metrics.py
- datadog/api/monitors.py
- datadog/api/resources.py
- datadog/api/screenboards.py
- datadog/api/service_checks.py
- datadog/api/tags.py
- datadog/api/timeboards.py
- datadog/api/users.py
- datadog/dogshell/__init__.py
- datadog/dogshell/dashboard_list.py
- tests/unit/api/helper.py
- tests/unit/api/test_api.py
This PR adds the new API endpoints for managing dashboard lists:
- Get all dashboard lists: `GET dashboard/lists/manual`
- Get dashboard list: `GET dashboard/lists/manual/{dashboard_list_id}`
- Create dashboard list: `POST dashboard/lists/manual`
- Update dashboard list: `PUT dashboard/lists/manual/{dashboard_list_id}`
- Delete dashboard list: `DELETE dashboard/lists/manual/{dashboard_list_id}`
- Get dashboards for dashboard list: `GET dashboard/lists/manual/{dashboard_list_id}/dashboards`
- Add dashboards to dashboard list: `POST dashboard/lists/manual/{dashboard_list_id}/dashboards`
- Update dashboards of dashboard list: `PUT dashboard/lists/manual/{dashboard_list_id}/dashboards`
- Delete dashboards from dashboard list: `DELETE dashboard/lists/manual/{dashboard_list_id}/dashboards`
> [dashboard list] Add new endpoints + dog cmd for dashboard lists

- datadog/api/metrics.py
This updates the [datadogpy docs](http://datadogpy.readthedocs.io/en/latest/#datadog.api.Metric.send) to reflect the correct metric types that are available in the `api.Metric.send()` API: `gauge` `count` and `rate`. I incorrectly passed in `counter` which silently uses `gauge` instead.
As far as I can tell this is correct because of these documents:
- https://docs.datadoghq.com/developers/metrics/#how-do-submission-types-relate-to-datadog-in-app-types
- https://docs.datadoghq.com/api/?lang=python#post-time-series-points
> Update type definition for api.Metric.send(...)

- datadog/__init__.py
- tests/unit/dogstatsd/test_statsd.py
Dogstatsd supports handling payloads from a UNIX socket. Combined with origin detection, this makes `dogstatsd` aware of the containers that submit metrics (and therefore add associated tags to those points).
> Add support for `statsd_socket_path` in initialize function

- datadog/dogstatsd/base.py
- tests/unit/dogstatsd/test_statsd.py
This makes the python statsd client behavior consistent with the ruby and
golang statsd clients, which also include the client level tags on service
checks.
> Append all statsd client level tags to status checks.

- datadog/__init__.py
- tests/unit/api/test_api.py
> Change API endpoint

- datadog/dogshell/wrap.py
👋
Observed behaviour: 
When `dogwrap` runs in a Python 3 environment with `submit_mode=all`, and there is both `stdout` and `stderr`, the following error occurred: 
```shell
...
top_third=text[:max_len / 3],
TypeError: slice indices must be integers or None or have an __index__ method
```
Cause: 
This is because in Python 3, `int / int` no longer returns an int, it returns a float. And floats are invalid index values.
Solution: 
This integer division functionality can be forced by using `//` rather than `/` in both Python 3 and Python 2. (Tested in Python 2.7.12, Python 3.5.2; operator introduced in Python 2.2+ ([PEP238](https://docs.python.org/3/whatsnew/2.2.html#pep-238-changing-the-division-operator))
This change has only been tested manually, because it doesn't appear `dogwrap` is …
> Force integer division for truncation of stdout/stderr in dogwrap

- datadog/dogshell/wrap.py
Observation: 
When using `dogwrap` (via a Python 2 `pip install`) to run commands via `cron`, in cases where the `submit_mode` is set to all, it was expected that both `stdout` and `stderr` would appear in DataDog. This was not the case. 
The event would appear, but the `stdout`/`stderr` was lost 
The output would appear correctly if the `dogwrap` command was run in the shell, just not in `cron`
Cause: 
In Python 2, the string from the `OutputReader` was being inspected for an `encoding`. If this command was run within a shell, an encoding was found (in this case, `ANSI_X3.4-1968`). However, when run from `cron`, no encoding was detected. Thus, attempting to execute a string decode (`line.decode(None)`) resulted in an error. 
In Python 3, the encoding inspection defaults to UTF-8, which …
> Default to utf-8 when no encoding type found parsing dogwrap output

- CHANGELOG.md
- datadog/api/monitors.py
- setup.py
Adds monitor search and monitor groups search API endpoints.
Docs:
https://docs.datadoghq.com/api/?lang=python#monitors-search
https://docs.datadoghq.com/api/?lang=python#monitors-group-search
> Add monitor and monitor groups search API endpoints

- README.md
Customer got stuck trying to configure StatsD, because they didn't realize the Agent needed to be running in order to get library working.
Adds one line note, referring back to documentation where we show how StatsD works, along with further instructions for configuration.
> Add note about the Agent running for StatsD

- .travis.yml
- datadog/dogstatsd/base.py
Warning was raised while running tests against my library with `-Wall` using `datadogpy==0.22.0`. It seems like the intention was to escape the `\`.
```
/tox/py36-django20/lib/python3.6/site-packages/datadog/dogstatsd/base.py:306: DeprecationWarning: invalid escape sequence \:
return string.replace('\n', '\\n').replace('m:', 'm\:')
```
> Silence deprecation warning

- datadog/dogstatsd/context.py
This simplifies troubleshooting.
> Use instance variable instead of overwriting a method.

- datadog/dogshell/__init__.py
Would check `DATADOG_APP_KEY` and `DATADOG_API_KEY` environment variables before using `~/.dogrc`.
Fix #144.
> [dogshell] use env vars for api_key and app_key

- datadog/dogstatsd/base.py
This avoid cases where the buffer is initialised but then doesn't receive any
packets to send before it's flushed. That can either be because of conditional
sending of metrics or because a sample rate is used which means no packets has
been generated this time around. In those cases an empty UDP packet is still
sent when the buffer is flushed.
This fixes that by checking if there are any packets to send before attempting
to send them off.
> Check if there are packets to send before sending an empty UDP packet

- MANIFEST.in
As of now, `tests/unit/dogstatsd/fixtures/route` is missing.
Follow-up to https://github.com/DataDog/datadogpy/pull/259.
> Completely include tests/ in PyPI tarball

- datadog/api/__init__.py
- datadog/api/distributions.py
- datadog/api/format.py
- datadog/api/metrics.py
- datadog/threadstats/base.py
- datadog/threadstats/constants.py
- datadog/threadstats/metrics.py
- datadog/threadstats/reporters.py
- tests/unit/api/test_api.py
- tests/unit/threadstats/test_threadstats.py
Based on https://github.com/DataDog/datadogpy/pull/308. 
Move distributions to its own `api.Distribution` resource.
Thanks again @jbarciauskas
>  Add support for distributions to threadstats and the API

- datadog/__init__.py
- datadog/threadstats/__init__.py
- datadog/threadstats/aws_lambda.py
- tests/performance/test_lambda_wrapper_thread_safety.py
- tests/unit/threadstats/test_threadstats.py
Wrapper to automatically initialize & flush in AWS lambda functions.
Example of a lambda:
```
from datadog import datadog_lambda_wrapper, lambda_stats
@datadog_lambda_wrapper
def my_lambda_handle(event, context):
lambda_metrc("some_metric", 10)
```
> Add decorator for AWS lambda

- datadog/api/http_client.py
- datadog/threadstats/aws_lambda.py
- tests/unit/api/helper.py
- tests/unit/api/test_api.py
Adds a new HTTPClient: `RequestClientKeptAlive`. It keeps the `requests` session alive.
Adds a no-op POST request on lambda_wrapper initialization: this initializes `RequestClientKeptAlive`'s connection to our endpoint at the beginning of the lambda executions instead of at the end: this enables to us to use an async initialization.
Note: the connection to our endpoint is kept alive across multiple invocations of the same lambda thanks to AWS's context reuse.
> Lambda wrapper - start TLS connection on init & RequestClientKeptAlive

- .travis.yml
- tox.ini
and have Travis use it
Also removed the env for Python 3.3 since it is EOL. I'll officially deprecate it in a separate PR
> Add support for tox

- datadog/api/api_client.py
This PR removes a string conversion that causes https://github.com/DataDog/datadogpy/issues/223. It is reasonable to assume that the values of the `errors` Array are strings, so this conversion is unnecessary, and it causes a `UnicodeEncodeError` in Python 2 if the API response contains non-ASCII characters.
Tested with Python 2.7.15 and 3.7.2.
> Remove redundant string conversion to prevent UnicodeEncodeError

- datadog/dogstatsd/base.py
- tox.ini
Attempts to fix https://github.com/DataDog/datadogpy/issues/212.
> Handle more socket exceptions

- datadog/__init__.py
Just adds a line to spell out how proxies should be configured. This was requested by a customer.
> add example of proxy config to docs

- datadog/dogshell/comment.py
Changed `handle` to be a required/positional argument
https://cl.ly/52b910cbb19e
https://cl.ly/ef45d5553172
Re this ticket: https://trello.com/c/ZehkVOzr/2805-running-dog-command-dog-comment-post-without-handle-returns-error-none-is-not-of-type-string
> Comment handle requirements

- datadog/dogshell/monitor.py
These subcommands read a filename from the command line, and then use
specified file for all values.  These features allow a workflow of `dog
monitor show <id> > monitor_id.json && dog monitor fupdate
monitor_id.json`.  This workflow allows version control of all monitors,
as well as repo-driven updates.
> add monitor subcommands that work from file

- datadog/__init__.py
- datadog/dogstatsd/base.py
- tests/unit/dogstatsd/test_statsd.py
Add environment variables support for Client configuration
Support of 3 environment variables for Client configuration:
`"DD_AGENT_HOST"` used to provide the Agent hostname.
`"DD_DOGSTATSD_PORT"` used to provide the DogStatsD port.
`"DD_ENTITY_ID"` used to provide an identifier to the Client.
If Client constructor's arguments are not set, prioritize `"DD_AGENT_HOST"` and `"DD_DOGSTATSD_PORT"` over default values.
Add `"DD_ENTITY_ID"` to tags with the tag name `dd.internal.entity_id`.
> add env vars support for dogstatsd host, port and entity id

- datadog/threadstats/aws_lambda.py
Previously a final flush would not occur if an uncaught exception occurred in the function wrapped by the Lambda wrapper. Now we always flush, just like mommy taught us!
> Lambda wrapper - Always flush, even on exceptions

- datadog/dogshell/wrap.py
Ignore any decoding errors incurred when the process being run emits content that isn't decode-able by the filesystem's locale. 
Python docs describing the change being made - https://docs.python.org/3/library/stdtypes.html#bytes.decode
Resolves https://github.com/DataDog/datadogpy/issues/371
> [Dogwrap] Ignore decode errors

- datadog/api/infrastructure.py
- doc/source/index.rst
Adds `Hosts` to `index.rst` so that we can get documentation of `Hosts.search()`, which is the preferred method over the sort-of-deprecated `Infrastructure.search(q="hosts:")` method. Also fixes a spelling error in `Infrastructure`.
> adding Hosts endpoint to docs

- datadog/api/format.py
> Import Iterable from collections.abc on python3

- datadog/api/resources.py
- tests/unit/api/helper.py
- tests/unit/api/test_api.py
The EU instance (api.datadoghq.eu) refuses GET requests with a body (even if empty JSON dict `{}`) and responds with `400 Bad Request`. 
This PR simply set the body to `None` when making GET requests.
Fixes #375
> Do not send JSON body in GET requests

- datadog/api/distributions.py
- datadog/api/events.py
- datadog/api/metrics.py
- tests/integration/api/test_api.py
- tests/unit/api/helper.py
- tests/unit/api/test_api.py
Add ability to set `attach_host_name` to false when sending metrics, events and distributions
Also adds some tests and fixes a bunch of flake8 while I was there
Resolves #325
> Add ability to not attach_host_name to metrics, events and distributions

- datadog/dogshell/wrap.py
- tests/unit/dogwrap/fixtures/proc_out.txt
- tests/unit/dogwrap/test_dogwrap.py
- Arguments are bytes, so the join must be made on a binary string, otherwise python will try to convert and can encounter errors.
- Stop decoding lines before writing to stdout, since `write` expects bytes.
- Move decoding the output to the end of the execution, to make sure we won't raise exceptions while command is still running, which can cause unexpected behavior, like in issue #371 .
Resolves #371, closes #223
> Better string handling for dogwrap

- datadog/api/api_client.py
- tests/integration/api/test_api.py
Reference: https://docs.datadoghq.com/api/?lang=python#rate-limiting
These changes make it so the response headers returned by Datadog are passed to the user. The rate-limit headers can be useful for monitoring usage and backing off when necessary.
> Return Rate Limit Headers 

- datadog/dogshell/timeboard.py
The `_escape()` method assumed it always would be receiving a string, but if
there is no description set on a timeboard it would instead be set to `None`.
This handles those cases by instead making the function return an empty string
in case the input is False-y - ie. `None`.
> Allow listing timeboards with empty descriptions

- datadog/util/hostname.py
This fixes an issue we're seeing in ECS, where every time a new container starts, we get something like this printed to stderr:
> hostname: 91d9cd0c1b70: Host not found
Since Datadog's log UI treats everything on stderr as ERROR level by default, that means we get output like this (for a job that runs every minute):
I have no idea _why_ `hostname` is printing this error, but I can confirm that this change fixes it.
> No annoying hostname output

- datadog/__init__.py
- tests/unit/api/test_api.py
> Do not override API parameters with default when calling initialize if they are already set

- datadog/dogshell/service_check.py
The --tags argument was not working, this allows a user to submit a service check with more than just the host tagged.
Based on @gordlea's work, supersedes #348
> Fixes the --tags argument for service_checks in dogshell

- datadog/__init__.py
- tests/unit/dogstatsd/test_statsd.py
Added a new parameter to the Initialize method in order to update the statsd object default namespace.
> DD Initialize now can update the statsd object default namespace

- README.md
- datadog/__init__.py
- datadog/dogshell/__init__.py
- datadog/threadstats/aws_lambda.py
- tests/unit/api/test_api.py
Adds a check for the `DD_` prefix to environment variables we have in [Datadog APM](https://docs.datadoghq.com/agent/docker/apm/?tab=java#docker-apm-agent-environment-variables).
Also adds an explanation with an example of how to use environment variables in `datadogpy` to README.
> Add DD_ prefix from Datadog APM with instructions

- datadog/api/api_client.py
Properly extend the response headers to the response object list. 
Resolves:
```
Traceback (most recent call last):
File "test.py", line 14, in <module>
print (api.Monitor.get_all())
File "/usr/local/lib/python3.7/site-packages/datadog/api/monitors.py", line 57, in get_all
return super(Monitor, cls).get_all(**params)
File "/usr/local/lib/python3.7/site-packages/datadog/api/resources.py", line 181, in get_all
return APIClient.submit('GET', cls._resource_name, api_version, **params)
File "/usr/local/lib/python3.7/site-packages/datadog/api/api_client.py", line 161, in submit
response_obj['response_headers'] = response_headers
TypeError: list indices must be integers or slices, not str
```
issues on endpoints that had response headers returned. 
Fixes …
> Extend response headers to response

- datadog/api/api_client.py
- tests/integration/api/test_api.py
Reverts the Feature of returning headers to the user - https://github.com/DataDog/datadogpy/pull/378/files
Revert the original fix - https://github.com/DataDog/datadogpy/pull/397
> Revert returning Headers

- README.md
In some environments, a non-ASCII character causes a failure when pip installing datadog.
I could not replicate on my local OSX machine, but I have a Docker image based on Ubuntu 14.04.5 LTS that fails reliably with the character in the README.
I would add a test, but the tests already fail in my Docker environment for the same reason, I'm not sure what exactly in the environment causes it.
Edit: I spent some time looking at the logic used to determine an encoding for `open()` when none is specified.
On a Unix system, without `CODESET` available, it looks for four environment variables `'LC_ALL', 'LC_CTYPE', 'LANG', 'LANGUAGE'`. If none of those are set, it defaults to `ascii`. The container where the build fails has none of those four set.
While this is an environment issue, I still …
> Replace non-ASCII apostrophe

- datadog/dogshell/wrap.py
- tests/unit/dogwrap/test_dogwrap.py
The options parser returns a list of `str`, which was getting joined with a `bytes` string. There were also two places where `bytes` were being written to stdout and stderr.
Fixes #394
> [dogshell] Fix dogwrap unicode option parsing on python 3

- datadog/api/__init__.py
- datadog/api/api_client.py
This PR adds a new `get_http_respone` top level function to the `api` module. The primary goal is to allow users to call this after any other api call to see the response of the previous call. This allows you to inspect things like status_code, headers, etc and currently just returns the `requests` response - https://2.python-requests.org/en/master/api/#requests.Response
This approach also has the benefit of not adding response metadata to the actual data object returned by the client. 
The code would look something like this:
```
api.Monitor.get_all()
resp = api.get_http_response()
```
> Add new top level `api` function to get the response object of last request

- setup.py
This will add more links in the "Project links" section in the left hand
sidebar on the PyPI page, liking to the bug tracker, documentation and source
code. It will make it easier for users of the library and automated package
updating tools to figure out what's changed, where to report issues and where
to find the documentation for the package.
> Add project URLs to package metadata

- datadog/__init__.py
- datadog/api/__init__.py
- datadog/api/api_client.py
- tests/unit/api/test_api.py
Reverts https://github.com/DataDog/datadogpy/pull/412 and re implements in a different way. 
This PR makes the approach threadsafe while keeping backwards compatibility by using a configuration option passed through the global init. `return_raw_response` is set to false by default, but when its explicitly enabled, we return the decoded response as well as the raw response object from the `submit` method.
> Add init option to add raw response to return values

- datadog/threadstats/aws_lambda.py
The lambda wrapper in the thread stats library is now deprecated for the new [datadog lambda layer](https://github.com/DataDog/datadog-lambda-layer-python), which has the same functionality. We want to introduce a warning so people will know to upgrade.
> Add deprecation warning to old aws lambda threadstats integration

- datadog/api/exceptions.py
- datadog/api/http_client.py
This PR adds support for handling a 401 status code in an API response and treats the response as an `ApiError` the same way other 400 level status codes are handled.
> Add support for handling a 401 status code response as an ApiError

- datadog/api/users.py
Updated the users resource name to be pluralized, matching the newly encouraged plural version of the endpoint
> [users] Updated users resource name to match new plural endpoints

- datadog/api/api_client.py
- datadog/util/compat.py
- tests/unit/api/helper.py
- tests/unit/api/test_api.py
> Treat API_HOST as URL

- datadog/api/exceptions.py
- datadog/api/http_client.py
- datadog/dogshell/common.py
Allows for configuring a proxy for Dogshell.
sample ~/.dogrc that utilizes a proxy
```
[Connection]
apikey = xxx
appkey = yyy
api_host = https://api.datadoghq.com
[Proxy]
http = http://localhost:3128/
https = http://localhost:3128/
```
Someone asked in public slack how to use dogshell with a proxy.
Told him he could set `api_host` to a reverse proxy. Then, I looked at the code and found that dogshell uses `datadog.api.initialize` [here](https://github.com/DataDog/datadogpy/blob/master/datadog/dogshell/__init__.py#L72-L73)
...and that `initialize` already takes in proxies as a parameter [here](https://github.com/DataDog/datadogpy/blob/master/datadog/__init__.py#L44-L46)
... so I figured I could just find a way pass the information from dogrc
> [dogshell] enable proxy

- datadog/util/config.py
Makes sure that the config file descriptor is closed once read.
> config: do not leak file descriptor when reading config

- datadog/threadstats/periodic_timer.py
The current hack does not work, as I'm still able to see such messages in the
log:
Exception in thread Thread-1 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
File "pyenv/versions/2.7.12/lib/python2.7/threading.py", line 801, in __bootstrap_inner
File "python/lib/python2.7/site-packages/datadog/threadstats/periodic_timer.py", line 43, in run
File "pyenv/versions/2.7.12/lib/python2.7/threading.py", line 614, in wait
File "pyenv/versions/2.7.12/lib/python2.7/threading.py", line 355, in wait
<type 'exceptions.TypeError'>: 'NoneType' object is not callable
This changes the current code to leverage the same hack that the `threading`
library uses: if the `sys` module is None, there's a good chance that's because
the interpreter is shutdown down.
This change …
> Fix periodic timer error on interpreter shutdown

- datadog/api/api_client.py
- datadog/api/graphs.py
- datadog/util/format.py
- tests/unit/util/test_format.py
Using `urljoin` led to some unexpected results depending on whether there are leading `/`.
Now uses a well defined and tested utility method, so no surprises
> Fix graph snapshot status endpoint

- datadog/dogshell/common.py
The current error handling would result in the errors and warnings from the API JSON response to be printed to `stderr` character by character (when the API would return a string and not a list).
> Fix error printing to stderr char by char

- datadog/__init__.py
- datadog/api/__init__.py
- datadog/util/hostname.py
- tests/unit/api/test_api.py
> Hostname lookup in debug and on/off setup

- datadog/api/__init__.py
- datadog/api/api_client.py
- datadog/api/service_level_objectives.py
- datadog/dogshell/service_level_objective.py
- datadog/util/cli.py
- datadog/util/compat.py
- tests/integration/api/test_api.py
- tests/unit/api/helper.py
- tests/unit/api/test_api.py
Adds support for Service Level Objectives
MA-434
> add support for SLOs

- datadog/dogshell/monitor.py
- tests/integration/dogshell/test_dogshell.py
The `api.Monitor.update` endpoint doesn't actually require `query` or `type` so removing restrictions from the clients and updating the docs (based on a customer request).  
I updated the test in `test_dogshell.py` but wasn't able to get the test to run based on directions.  Happy to test more thoroughly but could use some guidance.
> updated reqs and test

- datadog/api/__init__.py
- tests/unit/api/test_api.py
> Add _return_raw_response to api module

- datadog/api/api_client.py
- tests/unit/api/test_api.py
Attempts to fix integration test failures. Follow up from #446.
Also assess that keys aren't in both params and headers.
> Fix keys in headers for some endpoints

- datadog/dogstatsd/base.py
- tests/unit/dogstatsd/test_statsd.py
Picks up https://github.com/DataDog/datadogpy/pull/231.
> Default sample rate

- datadog/util/hostname.py
- tests/unit/api/test_api.py
Adds test to ensure the `CfgNotFound` is not raised when `hostname_from_config` is set to true (and thus the second warning message is not emitted either).
> Add test to check CfgNotFound exception

- datadog/api/api_client.py
- tests/integration/api/test_api.py
`api.Distribution.send` no longer works after https://github.com/DataDog/datadogpy/pull/446, as endpoint `v1/distribution_points` still expects the api key in the URL parameter than header.
To reproduce:
```python
from datadog import initialize, api
options = {
'api_key':'<API-KEY>',
'app_key':'<APP-KEY>'
}
initialize(**options)
api.Metric.send(metric='my.test.metric', points=1)
api.Distribution.send(distributions=[{
'metric': 'my.dist.test',
'points': [(1573757950, [1.0])],
'host': None,
}])
```
> Set API Key in URL when submit distribution metrics

- datadog/api/__init__.py
- datadog/api/permissions.py
- datadog/api/resources.py
- datadog/api/roles.py
- tests/integration/api/test_api.py
This PR implements datadog's roles and permissions apis. This implements `v2` format of Datadog's apis. Tests are also included.
> Roles and Permissions APIs

- datadog/dogshell/dashboard.py
- datadog/dogshell/monitor.py
- datadog/dogshell/screenboard.py
- datadog/dogshell/timeboard.py
Hiding the real JSON exception to hide behind a generic Exception is not a good
practice and does not add any value.
> dogshell: remove Exception wrapping

- .azure-pipelines/unit_tests.yml
- tox.ini
Python3.4 is EOL and is not supported anymore by azure-pipelines
Python3.8 is out :)
> Remove Python3.4 from the test matrix, and add Python3.8

- datadog/api/roles.py
- tests/integration/api/test_api.py
- tests/integration/api/test_aws_integration.py
- tests/integration/api/test_azure_integration.py
- tests/integration/api/test_gcp_integration.py
- tests/integration/dogshell/test_dogshell.py
Adds a teardown logic to some integration tests to more safely cleanup in the event that the test encounters an assertionError. 
Bumps the retry_limit for the host tags integration test
Update the update `roles` test to now also send along the `id` as part of the payload as its required
Help ensure one test failure won't impact the next test run. 
Give the tags test more time to get the expected value back.
> Address possible flaky tests

- datadog/api/graphs.py
- datadog/api/monitors.py
- datadog/api/resources.py
- datadog/dogshell/monitor.py
- tests/integration/api/test_api.py
- tests/integration/dogshell/test_dogshell.py
@DataDog/monitor-app 
___
The `validate` endpoint can be used to check if a monitor definition is valid.
> [MA-665]  Add support for the `Monitor.validate` endpoint.

- datadog/api/downtimes.py
- datadog/dogshell/downtime.py
- tests/integration/api/test_api.py
- tests/integration/dogshell/test_dogshell.py
@DataDog/monitor-app 
___
https://docs.datadoghq.com/api/?lang=python#cancel-monitor-downtimes-by-scope
> [MA-669] Add support for `/v1/downtime/cancel/by_scope`.

- datadog/api/api_client.py
- datadog/util/format.py
- tests/unit/api/test_api.py
Addresses https://github.com/DataDog/datadogpy/issues/485. Manually tested too.
> Tag normalization

- datadog/api/exceptions.py
- tests/unit/api/test_api.py
This makes it easier to do the following:
```python
try:
except datadog.api.exceptions.DatadogException:
```
> feat(api): base class for all exceptions

- datadog/threadstats/base.py
Histogram metrics currently do not send the median aggregate: https://github.com/DataDog/datadogpy/blob/48a5a677c58bc7282a25061d811f445329ad1f17/datadog/threadstats/metrics.py#L86-L138
This PR corrects the in-line description of the Histogram function.
> Update histogram in-line description

- datadog/__init__.py
Per the documentation here https://docs.datadoghq.com/developers/dogstatsd/?tab=python#client-instantiation-parameters
It seems like you should be able to pass constant tags to the default statsd via the datadog initialize method. This just adds it and merges the list already in the default datadog.dogstatsd.statsd class similar to how the other statsd_* kwargs are handled
> Add statsd_constant_tags kwarg to datadog.initialize()

- datadog/dogshell/wrap.py
- tests/unit/dogwrap/test_dogwrap.py
Add a warning option based on exit codes provided by the user.
Warning exit codes should be a comma separated list such as `--warning_codes 123,345,678`.
> Add warning option for dogwrap based on exit codes

- .gitignore
- README.md
- datadog/dogstatsd/base.py
- tests/unit/dogstatsd/test_statsd.py
Adding base telemetry to the Python dogstastd. This allow troubleshooting of packet drop and performance issue by users.
> Adding telemetry to dogstatsd

- datadog/dogstatsd/base.py
This PR handles unexpected exceptions in `DogStatsd.close_socket()`.
Under certain obscure circumstances we get a crash on Python 3.6+ if the file descriptor vanishes before close is called.
See https://bugs.python.org/issue29343
> Handle OSError on socket.close on Python 3.6+

- datadog/dogshell/event.py
Enforce the default event priority value to `normal` when submitting an event via the API. 
The CLI help output stats that the default `priority` value used when
posting an event with `dog event post` is `normal`. That value isn't
enforced on the client side, and it seems leaving it to …
> [dogshell] Enforce the default 'normal' event priority client side

- datadog/dogstatsd/base.py
- tests/unit/dogstatsd/test_statsd.py
Fixes  #514 by catching `socket.error`and checking `errno == 11` (EAGAIN) and logs a warning without closing the socket.
As mentioned in the issue, `socket.send` raises a `BlockingIOError (socket.error on py2)` exception when the socket is "full" rather than a `socket.timeout` exception. Hence, we create a new branch in the try-raise where we catch `socket.error`, check the `errno` and log a warning without closing the socket. This works across both python 2 and 3.
I left the `socket.timeout` branch in place because I wasn't sure if there is another way to set up DogStatsd where `socket.timeout` is thrown when the socket is full. This way, the change shouldn't break compatibility for people who rely on that behaviour.
I considered not logging a message when a `socket.error` with `errno == …
> Handle EAGAIN socket error when dropping packets

- DEVELOPMENT.md
- tests/integration/api/test_api.py
https://datadoghq.atlassian.net/browse/MA-791
Add tests to confirm correct behavior of using options with the delete method in the client.
> Add tests for options on delete

- datadog/dogshell/__init__.py
- datadog/dogshell/wrap.py
- setup.py
/usr/bin/dog conflicts with the existing sheepdog package in common
Linux distributions. dogshell seems like a sensible choice since
it's already called that in the source module.
> Alias `dog` script names as `dogshell`

- datadog/api/service_level_objectives.py
Fix docstring to match the the default arg `limit` of 100
Fix docstring to match the the default arg `limit` of 100
N/A
N/A
N/A
Simple docstring change
N/A
> Fix ServiceLevelObjective.get_all limit default in docstring

- .gitignore
- README.md
- datadog/dogstatsd/base.py
- tests/unit/dogstatsd/test_statsd.py
Revert dogstatsd telemetry added in #505 
fixes #528
> Revert dogstatsd telemetry

- .gitignore
- README.md
- datadog/dogstatsd/base.py
- datadog/util/config.py
- tests/unit/dogstatsd/test_statsd.py
This PR remove the namespace for the telemetry metric to avoid counting them as custom metrics.
We also only flush the telemetry once every 10s (by default) to mirror the behavior from other Dogstatsd clients.
> Remove namespace telemetry

- datadog/dogshell/wrap.py
- tests/unit/dogwrap/test_dogwrap.py
This PR addresses a bug in the timeout handling code in the dogwrap script (#537). If the `--timeout` argument is used and the child process does not exit before the timeout expires, a syntax error was thrown and no event was sent to the Datadog API.
I fixed the `print` syntax within the timeout handling, and also ensured that the `stdout` and `stderr` of the child process are still collected if the process times out (this was skipped previously).
I added tests for this behavior, using mocks to simulate different subprocess behavior. (I originally tried to actually run a child process in the tests, but the behavior for signal handling in Azure devops seemed different from local. Someone with more experience in this CI environment could probably add more comprehensive testing 😄)
I also ran …
> Fix syntax error in dogwrap timeout handler and always collect output (#537)

- datadog/dogshell/wrap.py
- tests/unit/dogwrap/test_dogwrap.py
Allow setting the API key for dog wrap via the `DD_API_KEY` environment variable like for other Datadog products.
> Support DD_API_KEY environment variable in dogwrap

- datadog/api/constants.py
Closes #99 by adding a class `MonitorType` with constants for the allowed values
> Add enum for monitor types

- datadog/threadstats/base.py
- datadog/threadstats/metrics.py
- tests/unit/threadstats/test_threadstats.py
Closes #131 
Add `Set` class and `set` method to threadstats object to support set metrics in threadstats
unit tests
> Add `Set` metric type to threadstats

- datadog/dogstatsd/base.py
- tests/unit/dogstatsd/test_statsd.py
Adds support for `DD_ENV`, `DD_SERVICE`, and `DD_VERSION` to be used for setting `{env, service, version}` as global tags.
The statsd client will now also read from the environment variables above to set global tag configuration. The tags are limited to the set of `{env, service, version}`.
If there is a better way to set global tag configuration from environment variables, I'll gladly make the change. I largely drew upon the existing pattern I saw.
None that I can think of - the changes are additive in nature.
Unit tests.
None.
> Add support for DD_ENV, DD_SERVICE, and DD_VERSION environment variables

- datadog/api/aws_integration.py
- tests/integration/api/cassettes/TestAwsIntegration.test_update.yaml
- tests/integration/api/test_aws_integration.py
Adds `excluded_regions` field to AWS API client library for create/update. This will store excluded regions as part of AWS account data in integration config, which will be excluded by AWS crawlers from metric collection
https://datadoghq.atlassian.net/browse/AWS-344
Updating docs to …
> Add excluded_regions to POST/PUT AWS lib

- datadog/dogshell/wrap.py
- tests/unit/dogwrap/test_dogwrap.py
> Fix decode attribute error with options for py3

- .azure-pipelines/unit_tests.yml
- .gitignore
- MANIFEST.in
- datadog/__init__.py
- datadog/api/__init__.py
- datadog/api/format.py
- datadog/api/http_client.py
- datadog/dogstatsd/context.py
- datadog/dogstatsd/context_async.py
- datadog/util/compat.py
- datadog/util/hostname.py
- mypy.ini
- setup.py
- tox.ini
This PR begins to address #311 by adding initial support for Python type hints and type checking via Mypy.
This PR updates the codebase to support Mypy type checking and includes type hints for a couple of functions. Before adding type hints to the entire codebase, I wanted to share these initial changes and see if this is a direction that maintainers want to move in. This PR can be merged on its own (with follow-up PRs to add additional type hints), or I'm also happy to continue adding type hints here before merge.
Type hints use the comment-based syntax described in [PEP 484](https://www.python.org/dev/peps/pep-0484/) to be compatible with both Python 2 and 3. Other changes to the codebase were necessary in order to fix a few Mypy errors (commented in the code and noted below).
The …
> Initial support for Python type hints and Mypy type checking

- datadog/dogstatsd/base.py
- tests/unit/dogstatsd/test_statsd.py
It improves the packetization while sending batched metrics with packet size adjusted to prevent fragmentation while maximizing payload usage. Telemetry is sent in separate packets, once every 10 seconds won't impact overall performance. API is backward compatible, `max_buffer_size` has been deprecated but not removed, warning are logged if the parameter is used when building `Dogstatsd` objects.
It adds sending heuristic based on current buffer length. Some approximation regarding the actual bytes sent on wire include unicode character encoding (note that the telemetry is not accounting for that either).
Better optimal packet size detection could have been considered but it seems overkill, moreover the settings can be overridden.
Unit tests, integration tests, manual tests, packet …
> Size-based packetization for dogstatsd batched metrics 

- datadog/dogstatsd/base.py
- tests/unit/dogstatsd/test_statsd.py
Fix inversion while using constants in dogstatsd client.
N/A
N/A
Issue was observed while capturing packet that were bigger than expected.
N/A
> [dogstatsd] Correct inverted constants

- setup.py
Fixes import errors when using `datadog` wheel build with Python versions older than 3.5.
Fixes #571 
Adds explicit `typing` and `configparser` dependencies regardless of Python version, in order to allow a single `py2.py3` wheel build to work correctly.
An alternative solution is to create multiple wheel builds for Python < 3.5 and Python >= 3.5. This solution seemed simpler and doesn't require the build/release process to change. 
There are two more lightweight dependencies that aren't actually necessary for Python 3.5+ installations.
I reproduced the import errors described in #571, and saw that they were fixed by installing `typing` and `configparser`. I added the two new dependencies to `setup.py` and ran the unit and integration tests in Python 2.7 and 3.8. Finally, I created a …
> Add `typing` and `configparser` dependencies for python versions that need it

- datadog/api/http_client.py
- tests/integration/api/cassettes/TestDatadog.test_user_agent.yaml
- tests/integration/api/test_api.py
- tox.ini
Makes the user-agent header more useful.
> Improve user-agent header to include telemetry information

- setup.py
Fixes install errors on python 2 with pip<9
Fixes #584
Specifies the dependency on `configparser` to explicitly be `configparser<5`
Ideally this restriction would only be imposed when necessary (pip<9 is being used), but I don't believe there's a way to dynamically alter package requirements based on the version of pip being used.
Missing new features backported through configparser if they ever reintroduce python 2 support in versions >= 5
Built a new python 2 wheel with `python setup.py sdist bdist_wheel`
Created a virtual envrionment with python 2.7.12 and pip 8.1.1
Installed the newly created wheel file into that virtualenvironment using that older version of pip
N/A
N/A
> Use Python 2 compatible configparser explicitly

- datadog/dogstatsd/base.py
Add sock.setblocking(0) for UDP socket when connecting to a dogstastd server.
It resolve a blocking situation that was happening with internal test, making half test job stuck and ultimately failing after hitting the 1h timeout.
cf. above.
N/A
None identified so far.
Manual tests.
Test pipelines are all green with this change.
IPv6 seems unsupported for dogstatsd communication, should be fixed.
cf. PR title
> [dogstatsd] sock.setblocking(0) for UDP socket

- README.md
- datadog/dogstatsd/base.py
Closes #576
Adds an environment variable to disable `statsd` metric collection in certain cases (e.g development).
Added an environment variable called `DD_DOGSTATSD_ENABLE` that is set as `True` by default.
Should be backward compatible.
> Add environment variable to disable statsd metric collection

- README.md
This will allow the link to work on the [PyPI page](https://pypi.org/project/datadog/), following the next release.
> Use absolute link for changelog in README

- datadog/threadstats/aws_lambda.py
- tests/unit/threadstats/test_threadstats.py
This pushes creation of the ThreadStats used by the lambda code to its first use, instead of doing it at import time.
Closes #608
> Delay creation of lambda ThreadStats

- datadog/api/synthetics.py
Change doc string and error message to use the correct name for the `public_ids` parameter of `delete_test`.
Correct an error message to use the proper name of a parameter.
Change doc string and error message to use the correct name for the `public_ids` parameter of `delete_test`.
N/A
N/A
Run code using incorrect type for parameter to ensure error message displays correctly.
Also updated documentation here: https://github.com/DataDog/documentation/pull/8640
Fix `Synthetics` `delete_test` parameter name in docstring and `ApiError` text.
> Fix Synthetics delete_test parameter name

- datadog/dogstatsd/base.py
- tests/unit/dogstatsd/test_statsd.py
In some esoteric setups or testing it might be useful to submit telemetry statistics to a different dogstatsd server. 
This PR allows to set a different destination for telemetry metrics flushed. 
No alternate designs were considered.
Added complexity to Dogstatsd constructor, could be confusing if not well documented.
Unit tests updated. Feature is being used for dogstatsd performance/feature testing currently.
None.
> [telemetry] optionally decouple telemetry destination from other metrics

- tests/unit/dogstatsd/test_statsd.py
Fix usage of mocks: solves 
```
self = <tests.unit.dogstatsd.test_statsd.TestDogStatsd testMethod=test_default_sample_rate>
def tearDown(self):
"""
Unmock the proc filesystem.
"""
>       self._procfs_mock.__exit__()
tests/unit/dogstatsd/test_statsd.py:131:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
.tox/py38/lib/python3.8/site-packages/mock/mock.py:1545: in __exit__
return exit_stack.__exit__(*exc_info)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ …
```
> use start and stop instead of __enter__ and __exit__

- datadog/dogstatsd/context.py
- datadog/dogstatsd/context_async.py
- datadog/threadstats/base.py
This makes sure the computed time is correct by using a monotonic clock source.
> [dogstatsd] use monotonic clock source when available for timers

- README.md
- datadog/dogstatsd/base.py
- datadog/threadstats/base.py
- doc/source/index.rst
Gives the docs some needed TLC.
- Add PyPI install instructions
- Add an initialization section with example
- Add usage sections with examples for each module
- Clarify the documentation and usage for ThreadStats
- Consistent formatting in examples
- Update the Get in Touch section
Built the docs locally and they looked alright.
> Update and improve documentation

- datadog/api/__init__.py
- datadog/api/logs.py
- tests/unit/api/test_api.py
This PR implement a feature which is mentioned at #611.
This PR implemented API wrapper of 'logs-queries/list' (c.f.
https://docs.datadoghq.com/api/v1/logs/) that returns list of logs which
are matched with specified log query.
This PR follows implementation of other API wrappers.
Yes. …
> Add logs listing feature

- tests/unit/dogstatsd/test_statsd.py
- tests/unit/dogwrap/test_dogwrap.py
This removes a few deprecation warnings from tests, including using str instead
of bytes, coroutine, and invalid regular expressions.
Closes #598
> Remove deprecation warnings

- datadog/dogstatsd/base.py
- tests/unit/dogstatsd/test_statsd.py
It can be super verbose, let's keep it but reduce from warning.
> Turn EAGAIN warning into debug

- datadog/api/api_client.py
- datadog/dogstatsd/base.py
- tests/unit/dogstatsd/test_statsd.py
Use the formatting provided by the logger instance to lazily format log messages. `log.info("test message: %s", "hello")` will only be formatted to `"test message: hello"` if the logger is configured to log `INFO` messages. If not, the formatting will be skipped. This is preferable to …
> Lazy log formatting

- datadog/dogstatsd/base.py
This adds back non blocking to UDP and sets non blocking before connect
like it was before.
> Fix blocking connections in dogstatsd

- .github/CODEOWNERS
Since the order of items in the CODEOWNERS is important (last matching
line takes precedence), having the `*` line near the bottom of the file
negates any specific patterns above it. By moving this pattern up to the
top of the file, we now ensure that the precedence of ownership is
correctly evaluated.
Moved global owner pattern to the top of the CODEOWNERS file
N/A
Can only be tested in subsequent PRs. When a PR is open from a matching pattern for an external team, a review from that external team should be adequate to merge the PR.
N/A
> [github] Fix precedence order in CODEOWNERS

- datadog/dogstatsd/base.py
- tests/unit/dogstatsd/test_statsd.py
In preparation for additional work for statsd client, some prep needs to be done to
the codebase to reduce chances of functionality breaking so tests of statsd have
been cleaned up in this PR
- No functional change on the client
- Unit tests were cleaned up to raise conformance score to pylint from ~6 to ~9
- Unit tests were reworked to use standard assertions instead of keyword assertions
- Some minor cleanup of the code was done (one test was fixed, some comments were outdated)
N/A
N/A
Running the tests should give the exact same output as before
AC-34
N/A
> [statsd] Clean up statsd tests

- datadog/dogstatsd/base.py
By precomputing the telemetry formatting string, we are able to gain
2-15% increase in throughput over the old code in both Python2 and
Python3.
Sample timing data:
```
$ ./time_flush.py
Using Python3
_flush_telemetry_orig: 6.24254 (baseline)
_flush_telemetry_new : 5.56866 (89.21%, 12.10% increase)
_flush_telemetry_orig: 5.78443 (baseline)
_flush_telemetry_new : 5.57556 (96.39%, 3.75% increase)
$ ./time_flush.py
Using Python2
_flush_telemetry_orig: 3.78670 (baseline)
_flush_telemetry_new : 3.47990 (91.90%, 8.82% increase)
_flush_telemetry_orig: 3.84288 (baseline)
_flush_telemetry_new : 3.51469 (91.46%, 9.34% increase)
```
Benchmark runner:
```python
#!/usr/bin/env python3
import sys
import timeit
print("Using Python" + str(sys.version_info[0]))
x = timeit.Timer("""
from datadog import …
```
> [statsd] Improve performance of telemetry serialization

- datadog/dogstatsd/base.py
- tests/unit/dogstatsd/test_statsd.py
Old code did not have locking around its `open_buffer()` and
`close_buffer()` operations which made those two methods not
thread-safe. This change fixes this and aligns this module with the
documentation.
Fixes https://github.com/DataDog/datadogpy/issues/439
Fixes https://github.com/DataDog/datadogpy/issues/601
We now have an `RLock` around buffer operations that prevents threads
from changing the buffer owned by another thread.
Overall performance decrease when sending 2+ metrics is within the `+/- 5%` margin of error:
```sh
$ /time_buffer_ops.py 
Using Python3
baseline: 6.19679 (baseline)
mod     : 6.02907 (97.29%, 2.78% perf increase)
baseline: 6.20096 (baseline)
mod     : 6.04097 (97.42%, 2.65% perf increase)
baseline: 6.05407 (baseline)
mod     : 6.12549 (101.18%, -1.17% perf …
```
> [statsd] Fix buffer operation thread-safety

- setup.py
This PR removes the unused dependency on [decorator](https://pypi.org/project/decorator/), which as far as I can tell is completely unused. It appears this library was introduced as a dependency in the first commit to this repo but never actually used directly.
This will help make installations faster and slimmer as well as reducing some maintenance (eg. see #646, where the datadogpy build was broken due to environment mismatches in this dependency).
Removes the unused dependency from the `setup.py` file. This will prevent it from being included at installation time of `datadogpy`.
N/A
If the decorator library is being used in some non-standard way, this could remove something we're relying on (note: see "Verification Process" for why I don't think this is the case).
I verified this …
> [Internal] Remove unused decorator dependency

- datadog/dogstatsd/base.py
- tests/unit/dogstatsd/test_statsd.py
Fixes handling of unicode data when sending events in dogstatsd
We now properly handle both the type and length calculation of such strings
Closes https://github.com/DataDog/datadogpy/issues/660
Tiny reduction in throughput
1. Add `print` to string composed in [`event()`](https://github.com/DataDog/datadogpy/blob/master/datadog/dogstatsd/base.py#L738)
2. Python2: `python2 -m unittest -vvv tests.unit.dogstatsd.test_statsd.TestDogStatsd.test_unicode_event`
3. Python3: `python3 -m unittest -vvv tests.unit.dogstatsd.test_statsd.TestDogStatsd.test_unicode_event`
> [dogstatsd] Fix unicode handling of event text

- README.md
- setup.py
- tests/performance/test_statsd_throughput.py
- tests/util/fake_statsd_server.py
- tests/util/system_info_observer.py
We previously had no good way to do a reasonably-accurate local benchmark
of the statsd code so this benchmark should allow us to collect some of
that data easily.
Features:
- Supports both Python2 and Python3
- Has multi-threading support
- Supports env var configuration
- Collects CPU, memory, latency, duration, packet metrics
- Has an included separate-process fake server to collect the data
- Server runs in a separate process from test code
- Both server and benchmark support UDP _and_ UDS transports
- Includes various sanity checks and warnings to highlight issues
with transport and/or packet drop
- Averages data over multiple runs and threads
Closes https://github.com/DataDog/datadogpy/issues/662
Addition of a benchmarking test for `statsd`
1. Install `psutil`
2. Run `python2 -m …
> [statsd] Add performance benchmark test for local testing

- .github/CODEOWNERS
Adds `agent-core` team to owners of `tests/perofrmance/test_statsd_*` files
Since these tests are effectively the counterpart to the statsd code
that is owned by agent-core, this change ensures that the performance
test ownership is consistent too.
> [github] Add agent-core as co-owners to statsd performance tests

- tests/performance/test_statsd_throughput.py
- tests/util/fake_statsd_server.py
Few issues were noticed when running the statsd benchmark on MacOS that needed
fixing
- Receive buffer of the socket is now increased to reasonable levels
(32k from 4k)
- Packet count warning was moot since we may send multiple metrics per
packet
- If `statsd.flush` method is available, call it when the threaded
sender exits to ensure that we are accounting for all of the metrics in
the results.
Run benchmark on MacOS with 10 threads via UDS and see the reduction in packet drops
> [tests] Improve statsd performance benchmark on MacOS platforms

- tests/performance/test_statsd_throughput.py
- tests/util/system_info_observer.py
Absolute values of RSS memory are not really useful as the setup may be
different before the observer is run.
We now initialize baseline rss/vms values
when the observer is created and we only record the relative difference
of the context-managed block.
> [tests] Use memory diffs from baseline in observer helper module stats

- datadog/util/format.py
- tests/performance/test_statsd_throughput.py
- tests/unit/util/test_format.py
Speeds up the tag normalization function. By being in the hot path in `statsd`, this improves the
performance of `statsd` significantly (~30% reduction in latency, CPU utilization, and benchmark duration across the board). 
Since this function is used in the [`submit()` API too](https://github.com/DataDog/datadogpy/blob/master/datadog/api/api_client.py#L153), it may offer significant performance improvement there as well.
- Old code uses a string for sanitization of tags instead of a compiled regex, causing an excessive CPU overhead. This has now been changed to use the pre-compiled version.
- Adds profiling support to the statsd benchmark
- Adds tests for `normalize_tags` function
Fixes https://github.com/DataDog/datadogpy/issues/671
None
- Run the attached tests with `python3 -m …
> [statsd] Improve tag normalization speed

- datadog/dogstatsd/base.py
- datadog/util/deprecation.py
- tests/unit/dogstatsd/test_statsd.py
- tests/util/fake_statsd_server.py
On a high-level, this PR:
- Enables buffering-by-default for `statsd` (300ms automatic flush cycle)
- Adds a `statsd.flush()` helper method
- Deprecates `statsd.open_buffer()` and `statsd.close_buffer()`
- Closes https://github.com/DataDog/datadogpy/issues/669
This change turns all sync handling of statsd data into buffered handling
with a thread that forces flushes at a specified interval (default:
300ms, configurable via `flush_interval` kwarg). Because we now do this
buffering by default, the functions `open_buffer()` and `close_buffer()`
are effectively low-level operations and have been deprecated.
To help backwards compatibility where a context manager (which flushes
automatically on exit of the context) is not used, we also now have a
`flush()` function that can be used to force …
> [statsd] Enable buffering by default for statsd

- tests/util/fake_statsd_server.py
Allows the `./tests/util/fake_statsd_server` module to be run directly from the shell
There may be times where having a quick fake standalone statsd server is
advantageous (e.g. writing/updating client docs). While this can be
achieved with some python scripts or the interpreter shell, it's much
easier for the user/developer just to invoke the script itself if
possible which is what this change enables.
To use this fake server you just invoke the script:
```
$ # UDS Server (default)
$ ./tests/util/fake_statsd_server.py
Listening via UDS on /tmp/dir/path/FakeServerabcd1234/fake_statsd_server_socket
$ # UDP Server
$ ./tests/util/fake_statsd_server.py udp
Listening via UDP on port 58445
```
Debugging is enabled by default which should print out the received packets to the
console when run.
- …
> [tests] Statsd fake server can now be run as a standalone script

- datadog/dogstatsd/base.py
- tests/unit/dogstatsd/test_statsd.py
Adds newline (`\n`) to all packets sent to the DogStatsd endpoint
To prevent processing of packets that are incomplete by the time they
reach the server for whatever reason, we now add a newline to end of
all of our packets so that the server can recognize and discard partial
messages/metrics.
One character additionally sent with each packet (minimal impact on buffered clients)
- Run the test suite (`python3 -m unittest -vvv tests.unit.dogstatsd.test_statsd.TestDogStatsd`)
Alternatively:
- Start a fake statsd server on a separate terminal (`./tests/util/fake_statsd_server.py UDP`) 
- Send a metric and ensure it has a newline at the end on the server's received packet output:
```sh-session
$ python3
>>> from datadog import initialize,statsd
>>> initialize(statsd_host="localhost", …
```
> [statsd] Always terminate packets with newline

- README.md
`tab`/`lang` language selection query params in doc links has been
changed to `code-lang` so this commit fixes those occurrences
in the README and links that redirected and lost those params in the
process.
Links in README are now fixed to use the expected lang query param
Clicking the links
> [docs] Fix README docs lang tab query param links

- datadog/dogstatsd/base.py
- doc/source/index.rst
- tests/unit/dogstatsd/test_statsd.py
Due to impact on users of other clients where buffering was enabled by
default, especially in environments and frameworks where `fork()` is
used we will for the time being disable buffering by default until a
decision is made on the path forward. Buffering can still be turned on
with `disable_buffering = False` flag it's just that for now it is
defaulted to `True`.
- Use of `DogStatsd` via `statsd` module-level object defaults to synchronous (un-buffered) metric sending.
- Use of `DogStatsd` via the default constructor defaults to synchronous (un-buffered) metric sending.
In discussion (TBD). We may revert this and use automated ways to detect environments
that are incompatible to thread-based buffering.
Lower performance in high-throughput environments.
Unit tests cover most of this: …
> [statsd] Disable statsd buffering by default

- .github/CODEOWNERS
Some utility and test paths were missing agent-core team as co-owners,
leading to unnecessary pings to the tools-and-libraries team. This
change adds agent-core as a co-owner team to paths that are frequently
worked on so that either team can provide approvals for PRs.
Additional paths added to the agent-core co-owners section
N/A
N/A
N/A
> [codeowners] Add `agent-core` as co-owner of relevant paths

- datadog/__init__.py
- datadog/dogstatsd/base.py
- tests/unit/dogstatsd/test_statsd.py
- Adds ability to set `statsd_instance.disable_buffering` flag after initialization
- Adds said flag as a argument to `initialize()` to be usable for the module-level `statsd` instance
While not likely to be useful currently, if/when we enable buffering on the `DogStatsd` clients
by default again we will want to have this feature already in place since the module level `statsd`
may not behave as expected in `fork()`-based environments. Because `datadog.initialize()` cannot
recreate the instance of the module-level `statsd`, we need a runtime setting for `disable_buffering`
instead of recreating the instance, making the implementation somewhat constrained in how it is
done.
As a side-effect, this change allow use of the module-level `statsd` instance with buffering enabled
which was …
> [statsd] Add ability to toggle `statsd.disable_buffering` state during runtime

- .azure-pipelines/unit_tests.yml
Remove Python 3.5 from the unit test matrix
Azure builders do not have this Python version anymore so they cannot
run against it. Given that 3.5 is EOL we will remove it from the test
matrix.
Python 3.5 support may get stale over time
CI/CD passes
> [tests] Remove Python 3.5 from unit-tested versions

- datadog/threadstats/base.py
- tests/unit/dogstatsd/test_statsd.py
- tests/unit/threadstats/test_threadstats.py
Changes `text` positional arg in threadstats to `message`
Closes: #707
Since 0.43, `statsd` has renamed a positional argument `text` to
`message`. When a user is invoking the API of this method with `kwargs` for named
parameters it no longer can be used to swap seamlessly between
`ThreadStats` and `DogStatsd`. This change ensures that both positional args
have the same names.
For more info: https://github.com/DataDog/datadogpy/issues/707#issuecomment-1028148626
Potentially a breaking change for users of ThreadStats if they use `event()` with
named positional args. Release notes are updated to make that clear.
CI/CD tests
- `ThreadStats().event()` and `DogStatsd.event()` now both use `message` instead of `text` as the name of the second positional argument
> [threadstats] Ensure `ThreadStats` and `DogStatsd` `event()` signatures match

- datadog/dogstatsd/base.py
- tests/unit/dogstatsd/test_statsd.py
When exiting the context or when manual close_buffer is invoked, we
should restore the buffering state that existed before the
context/manual buffer changes were applied.
Fixes: https://github.com/DataDog/datadogpy/issues/714
Buffering state is restored when buffer is manually closed or the managed context is left.
N/A
N/A
Unit tests cover the functionality but manual test can be done by following directions in the [upstream issue](https://github.com/DataDog/datadogpy/issues/714)
> [statsd] Restore buffering state when exiting context manager

- .azure-pipelines/unit_tests.yml
- .github/workflows/test.yml
- MANIFEST.in
- pyproject.toml
- tox.ini
This implements [PEP 621](https://www.python.org/dev/peps/pep-0621/), obviating the need for both `setup.py` and `MANIFEST.in`. Support has not landed in `setuptools`, so builds will now use `hatchling`. We also did this for all integrations: https://github.com/DataDog/integrations-core
This also drops support for EOL Python 3.x versions since `hatchling` and other build backends like `setuptools` have already done so. This will not break anything because `pip` only looks for version candidates that satisfy the `requires-python` field. Here are stats for the curious: https://pypistats.org/packages/datadog
Note that the `setup.py` file will be removed when we drop Python 2 since new-style editable installations require versions of `pip` that are Python 3-only. Basically, this is just for …
> Update package metadata

- datadog/dogstatsd/base.py
- datadog/dogstatsd/container.py
- tests/unit/dogstatsd/test_container.py
- tests/unit/dogstatsd/test_statsd.py
Adds `c:<id>` field holding the container ID so the agent can attach container tags.
- If `DD_ENTITY_ID` is set, we ignore the container field
- If `DD_ENTITY_ID` is not set and `DD_ORIGIN_DETECTION_ENABLED` is not explicitly set to false and the `origin_detection_enabled` param is not explicitly disabled, we try to get the app container ID by parsing `/proc/self/cgroup`. In case of success, the container field in will be set.
Wrote a small app importing the lib and sending metrics to agent 7.35 with origin detection client enabled - the metrics were tagged with container tags.
- Users should explicitly enable container tagging in the agent otherwise the agent ignores the container field. So even if the client sends the field automatically, the tagging won't be done without explicitly …
> feat: origin detection with container ID field

- datadog/dogstatsd/base.py
We currently use datadogpy library v0.44.0 and noticed tons of log volume coming from the base class file especially in the flush thread flow, causing log volume spike and masking useful information that would otherwise be gleaned from our logs. This PR downgrades the log level to debug, these lines serve little purpose in my humble opinion and could easily be replaced with a counter.
What inspired you to submit this pull request?
This change isn't a feature or a bug fix, but follows a process of better log hygiene. 
please refer to the questions above. 
Would be replace these log lines with simple statsd counter incr.
None
What process did you follow to verify that your change has the desired effects?
- How did you verify that all new functionality works as expected?
- How did you verify …
> [base] demote noisy log lines to debug level

- datadog/dogstatsd/base.py
- tests/unit/dogstatsd/test_statsd.py
As noted in #725, statsd.event() raises a general Exception in the event that an event payload is too long. This can lead to error swallowing. This PR changes this error block to raise a ValueError instead.
The statsd.event() method throws a different Exception (ValueError) in the event that a payload is too large. A test was added to test_statsd.py in order to ensure that the proper error is raised when appropriate.
Any exception could theoretically be raised, but ValueError seemed the most appropriate according to [Python's guidelines](https://docs.python.org/3/library/exceptions.html#TypeError). Alternatively, users of the datadog library could just catch the Exception but that is poor practice.
Users of the library who currently have code in place to catch a general Exception may have …
> [statsd] Raise ValueError instead of Exception when payload is too large

- .github/CODEOWNERS
Updates `CODEOWNERS` file with correct team references
`agent-core` no longer exists and the dogstatsd bits should be owned by @DataDog/agent-metrics-logs 
I believe `baklava` is an old name for @DataDog/documentation
> Updates CODEOWNERS for agent-core -> agent-metrics logs and baklava -> documentation

- .github/workflows/test.yml
- pyproject.toml
- tox.ini
Tox failing due to a bug with factor names, considers "pypy" and "3.8" conflicting. This changes the actions workflow to use pypy3.8 and pypy2.7 as the names instead, and also updates the github actions dependency versions.
> Tox error workaround with alternate pypy version names

- datadog/dogshell/__init__.py
- datadog/dogshell/common.py
- datadog/dogshell/wrap.py
It solves https://github.com/DataDog/datadogpy/issues/748.
Add dogwrap site option to send to US3 site.
N/A
N/A
Tested manually.
N/A
N/A
> Add dogwrap site option to send to US3 site

- datadog/api/api_client.py
- tests/unit/api/test_api.py
All endpoint supports it now, let's use headers everywhere.
> Use header for credentials everywhere

- datadog/dogshell/dashboard_list.py
- datadog/dogshell/service_level_objective.py
This fixes dogshell in 3.11
Closes #746
> Fix duplicate parsers in dogshell

- datadog/dogshell/__init__.py
- datadog/dogshell/common.py
- datadog/dogshell/wrap.py
Remove choice option type, instead fallback on user-supplied url if the string doesn't match a known site parameter.
> Add govcloud to site param descriptions, and add custom url fallback

- .github/workflows/test.yml
PyYaml 5.4.1 fails to build on py2.7 using cython >= 3. Unfortunately PyYaml 5.3.1 causes test breakage so we are unable to pin to that version.
See: https://github.com/yaml/pyyaml/issues/724
Since this is an outdated version of python and test specific transitive dependency, I think it should be okay for us to use constraints to build PyYaml using cython<3 without overhauling the tox configuration.
> Pin pyyaml for py2.7

- datadog/dogstatsd/base.py
- mypy.ini
- tests/integration/dogstatsd/test_statsd_sender.py
- tests/unit/dogstatsd/test_statsd.py
Add options to improve dogstatsd packet deliverability.
Allow dogstatsd socket to be used in a blocking mode with a timeout. This improves our chances to send the packet if the socket queue is full (e.g. after a burst in packets).
Add a background thread to handle the writes, with a queue to act as a buffer.
Together, this allows users to reduce dropped packets to zero while maintaining low latency for the user application, at the cost of higher cpu and memory usage.
> Add blocking socket mode and background sender

- datadog/dogstatsd/base.py
- tests/integration/dogstatsd/test_statsd_sender.py
- tests/unit/dogstatsd/test_statsd.py
Make it possible to enable new features from #787 on the global `statsd` instance.
Add setter methods to modify socket timeout and start the background sender thread.
> Add setters to configure the global instance

- datadog/dogstatsd/base.py
- tests/unit/dogstatsd/test_statsd.py
Add IPv6 support for hostnames and literal addresses.
Call `getaddrinfo` to parse and resolve an internet address before creating the socket. Try in a loop until one address succeeds.
For backwards compatibility, prefer ipv4 addresses: ipv4-only agent should still work even if hostname (e.g. `localhost`) resolves to both ipv4 and ipv6 address and ipv6 is preferred by the OS. This also matches behavior of Golang.
Address order specified in `gai.conf` is ignored, which may lead to inconsistencies with other applications.
> Add ipv6 support for dogstatsd

- datadog/dogstatsd/base.py
- tests/unit/dogstatsd/test_statsd.py
This patch makes the `client_transport` tag dynamic and updates it every time the `socket_path` property is updated.
`datadog.initialize` reassigns `socket_path` property on the global statsd instance, but the `client_transport` tag was computed in the constructor and never updated, causing client to misreport transport as udp when a unix socket was actually used.
> Fix stale client_transport tag

- datadog/dogstatsd/base.py
- tests/unit/dogstatsd/test_statsd.py
Update payload size when updating socket path
When `initialize` sets `socket_path`, thus switching from `udp` to `uds` transport, update `max_payload_size` to use payloads of optimal size for the transport.
> Update payload size when updating socket path

- datadog/__init__.py
- tests/unit/dogstatsd/test_statsd.py
Make sure statsd uses socket settings configured in `initialize`.
If the global statsd instance is used before initialize() is called (for example, statsd used to send metrics from a top-level of a loaded module), statsd instance will already have a socket open when we set connection parameters. To make sure they take effect, call close_socket().
> Close socket during initialization

- datadog/dogstatsd/base.py
- doc/source/index.rst
- tests/integration/dogstatsd/test_statsd_fork.py
- tests/integration/dogstatsd/test_statsd_sender.py
Use `register_at_fork` added in Python 3.7+ to transparently handle process fork when the client is using background threads.
Forking support is introduced in several layers:
- Per-instance hooks that can be called before and after fork() to disable and re-enable background threads and also flushes pending metrics.
- A weakset is added that tracks all instances of DogStatsd (an opt-out is provided in case unforeseen complications arise).
- Package level hooks that invoke fork hooks on all tracked instances.
- On Python 3.7+, the package level hooks are automatically registered with the Python runtime via `os.register_at_fork`.
This approach is similar to one used in dd-trace-py for handling forks.
> Improve forking support

- datadog/dogstatsd/base.py
- datadog/dogstatsd/container.py
- tests/unit/dogstatsd/test_container.py
Implements the support of Origin Detection when the container ID is unavailable from inside the container by using the inode resolution mechanic. The original Go implementation is here: [https://github.com/DataDog/datadog-go/pull/291](https://github.com/DataDog/datadog-go/pull/291)
If …
> Support inode resolution mechanism for Origin Detection

- datadog/dogshell/monitor.py
This PR adds the "restricted_roles" argument to the Monitors API endpoint (see https://docs.datadoghq.com/api/latest/monitors/#create-a-monitor)
Added the argument --restricted_roles to all the necessary parsers in order to be able to create/update/validate monitors with restricted …
> Add --restricted_roles option to Monitors API

- datadog/dogstatsd/base.py
- tests/unit/dogstatsd/test_statsd.py
Fix a potential deadlock in post_fork().
close_socket acquires _socket_lock, and calling it with the lock held deadlocks.
On top of this the warning did not prove very useful, as it would also trigger when the application is sending metrics from another thread when the process forks, in which case the warning is a bit misleading.
Without the warning there is no reason to check for socket being open, so just silently call close_socket() after the fork to avoid sharing the file descriptor between processes if another thread re-opened it between pre_fork() and fork itself.
> Fix potential deadlock during process fork

- datadog/dogstatsd/base.py
- tests/integration/dogstatsd/test_statsd_sender.py
Fix potential metric loss when open_buffer is combined with disable_buffering=False. 
Remove call to `_reset_buffer` from `open_buffer`.
When disable_buffering=False, the buffer may contain still unsent metrics, which are lost when we reset the buffer.
> Fix potential metric loss when open_buffer is combined with disable_buffering=False

- datadog/dogstatsd/base.py
- tests/unit/dogstatsd/test_statsd.py
Following [v1.3 protocol](https://docs.datadoghq.com/developers/dogstatsd/datagram_shell/?tab=metrics#dogstatsd-protocol-v13), allow passing timestamps along with the metric, which can mitigate the load on the agent when emitting a lot of metrics in a short time span.
Adds `gauge_with_timestamp` and `count_with_timestamp` to allow for passing metrics with timestamps. Also added `count` method which other clients have so that our clients all have similar methods.
> Support passing Unix timestamps to dogstatsd

- datadog/dogstatsd/metrics.py
- tests/unit/dogstatsd/test_metrics.py
This PR is for adding metric objects that will make aggregation easier by allowing us to have one Metric object instantiation for each [unique metric context](https://docs.google.com/document/d/1AoveWKoMQc65hYbvZ27uE7pQ_I5nsGfvv25EcNVPLvQ/edit#heading=h.no4x6fjugsh) that we can add samples to which will make aggregation easier. Existing behavior already exists in the [client side aggregation for GO ](https://github.com/DataDog/datadog-go/pull/139/files#diff-768b1bb89feaa2e5fedd4162f84c59c801610960af421ebd18e744d3f0adaa94)
Create metric object type (`MetricAgggregator`) that other metric objects (`CountMetric`, `GaugeMetric`, etc.) implement that will enforce the objects to implement functions `aggregate` and **potentially** `flush_unsafe`. This should also allow us to group the different …
> add metric object type

- .github/workflows/test.yml
- datadog/dogstatsd/aggregator.py
- datadog/dogstatsd/base.py
- datadog/dogstatsd/metric_types.py
- datadog/dogstatsd/metrics.py
- tests/unit/dogstatsd/test_aggregator.py
- tests/unit/dogstatsd/test_metrics.py
This PR adds the aggregator functionality for client side aggregation, it is pushing to a feature branch. This has already been implemented for the [GO client](https://github.com/DataDog/datadog-go/pull/139/files#diff-0d2ff0ba6d3144d1b0aea4da6445ea870b0ae794a5a5a8955dfa6c1b9150539a).
[Issue](https://datadoghq.atlassian.net/jira/software/c/projects/AMLII/boards/5315?selectedIssue=AMLII-1856)
Adds a class that periodically aggregates (this is not implemented yet as it will rely on functionality from the base.py class) metrics for a given `flush_interval` and then sends the aggregated metrics to intake. A metric will be aggregated if there was another [matching context](https://docs.google.com/document/d/1AoveWKoMQc65hYbvZ27uE7pQ_I5nsGfvv25EcNVPLvQ/edit#heading=h.no4x6fjugsh) sent within the …
> add aggregator 

- datadog/dogstatsd/base.py
- tests/integration/dogstatsd/test_statsd_fork.py
- tests/integration/dogstatsd/test_statsd_sender.py
- tests/unit/dogstatsd/test_statsd.py
Fix a potential deadlock on fork
If a fork happens while some thread is sending metrics and holds one of the locks, the lock would remain locked in the child process and would deadlock, either in the post_fork handler (when the post_fork hook tries to close the socket), or later (when user code tries to send a metric).
Work around the issue by resetting the socket and buffer locks in the child process. If those were locked in the parent at the time of the fork, the internal client state may be inconsistent, so we reset it as well.
With config lock, we can not reset the state to some known good state, and to avoid problems when fork is called while a thread modifies the client configuration, the config lock will be held across fork. Both the client and the parent can safely unlock it …
> AMLII-1842 Fix a potential deadlock on fork

- .github/workflows/test.yml
- datadog/__init__.py
- datadog/dogstatsd/aggregator.py
- datadog/dogstatsd/base.py
- tests/integration/dogstatsd/test_statsd_sender.py
- tests/unit/dogstatsd/test_aggregator.py
- tests/unit/dogstatsd/test_statsd.py
[Project description
](https://docs.google.com/document/d/11fPSNMnp5tMLRK16VgXa6FJ7fTpzggKevpiO6MsQ0H0/edit?usp=sharing)
This PR adds simple client side aggregation (aggregating metrics before they are received by the agent) for the python client. This PR combines two previous PRs …
> Add client side aggregation

- datadog/__init__.py
- datadog/dogstatsd/base.py
- tests/unit/dogstatsd/test_statsd.py
[Issue](https://datadoghq.atlassian.net/jira/software/c/projects/AMLII/boards/5315?selectedIssue=AMLII-1982)
enable the ability for buffering and aggregation to work at the same
Refactors code to enable aggregation/buffering at the same time. The aggregator will add the aggregated metrics into the buffer at the end of every flush interval before the buffer sends them to the agent. Aggregation/buffering share the same flush thread and flush interval.
aggregation and buffering seems tightly coupled, for [example](https://github.com/DataDog/datadogpy/blob/enable-buffering-aggregation-simultaneously/datadog/dogstatsd/base.py#L625)
Instead of killing the flush thread when buffering is disabled, (I assume) it needs to check if both aggregation and buffering is disabled before killing the flush …
> enable the ability for buffering and aggregation to work at the same

- .github/workflows/test.yml
- datadog/dogstatsd/buffered_metrics.py
- datadog/dogstatsd/metric_types.py
- tests/unit/dogstatsd/test_buffered_metrics.py
Adds BufferedMetric object to allow for extended aggregation (Distribution, Histogram, Timing metrics)
Based on off existing [Go code](https://github.com/DataDog/datadog-go/blob/master/statsd/metrics.go#L124)
Adds a `buffered_metrics.py` class that has all the properties that Distribution, Histogram and Timing metrics require
Added unit tests matching the [existing tests](https://github.com/DataDog/datadog-go/blob/master/statsd/metrics_test.go#L134C6-L134C28) 
1. This PR will merge onto a feature branch.
> add buffered_metrics object type

- .github/workflows/changelog.yaml
- .github/workflows/codeql-analysis.yml
- .github/workflows/labeler.yml
- .github/workflows/release.yaml
- .github/workflows/stale.yml
- .github/workflows/test.yml
- .github/workflows/test_integration.yml
> Set more specific GitHub token permissions on workflows.

- datadog/dogstatsd/base.py
- tests/unit/dogstatsd/test_statsd.py
Renaming the flush function caused a breaking change 
Issue [1](https://github.com/DataDog/datadogpy/issues/865), [2](https://github.com/DataDog/datadogpy/issues/858)
Add the flush function back to the api and revert renaming of another global variable.
Unit tests.
> [AMLII-2170] fix removed/renamed function flush

- tox.ini
Remove the black tox command.
Force the mypy tox env to one that is supported. 
Python 2.7 support is being retired in a number of the utilities we're using to perform code verification. Black, a python formatter, is currently unsafe to run for python < 3.3 and therefore the ability to do so is being disabled while python 2.7 is still under support for this repo. 
MyPy is currently version locked to support 2.7 static analysis, and fails to run successfully on python > 3.8. As such, it is defaulted to 3.8, the latest stable version that, at the time of writing, also boasts the most extensive pipeline support for the repo. 
We want a formatter for the project, so disabling black is not the solution we ultimately wish to run with. While it might be possible to isolate a specific older …
> Remove black while support is maintained for python 2.7

- .github/workflows/test.yml
- datadog/api/http_client.py
- tox.ini
Adds a third implementation for `HTTPClient` using `urllib3`.
The [`datadog-lambda-python`](https://github.com/DataDog/datadog-lambda-python) package depends on `datadogpy` for submitting metrics in certain cases. The package is used in AWS Lambda environments where resources are very …
> Provide urllib3 implementation of HTTPClient.

- datadog/dogstatsd/base.py
- datadog/dogstatsd/context.py
Fixes #797 by adding some types to `Dogstatsd.timed()` function.
1. Provides some types to `Dogstatsd.timed()` function and `TimedContextDecoratorManager`. 
2. This does not fully solve the issue with types not being preserved when using `timed` as a decorator, but typing that …
> Add type annotations to Dogstatsd.timed function and TimedContextManagerDecorator class

- datadog/dogstatsd/base.py
- tests/unit/dogstatsd/test_statsd.py
> updated broken tests

- datadog/dogstatsd/aggregator.py
- datadog/dogstatsd/base.py
- tests/integration/dogstatsd/test_statsd_sender.py
- tests/unit/dogstatsd/test_statsd.py
Includes full support for the unix://, unixstream://, and unixgram:// socket_path prefixes utilized by DD_DOGSTATSD_URL in preparation to support that feature.
Autodetects SOCK_DGRAM vs SOCK_STREAM for users currently providing a raw socket path.
Set up a datadog agent with both a datagram and a stream uds socket path.
Ensure that a client initialized with socket_path={socket_path} and socket_path=unix://{socket_path} can successfully transmit metrics/events/services to both types of sockets when socket_path is an absolute path and when socket_path is a relative path. 
Similarly ensure that socket_path=unixstream://{socket_path} can send to the stream socket and socket_path=unixgram://{socket_path} can send to the datagram socket. Confirm for both prefixes that sending to the wrong …
> Add UDS SOCK_STREAM support to the DogStatsD client

- datadog/__init__.py
- datadog/dogstatsd/aggregator.py
- datadog/dogstatsd/base.py
- datadog/dogstatsd/max_sample_metric.py
- datadog/dogstatsd/max_sample_metric_context.py
- datadog/dogstatsd/metrics.py
- datadog/util/format.py
- tests/unit/dogstatsd/test_max_sample_metrics.py
- tests/unit/dogstatsd/test_statsd.py
Implement the `card:` common field to DogStatsD Datagram spec. This new field is used to override the Agent cardinality.
Adds a new cardinality setting that can be either:
- Defined globally as an option
- Override on a per-metrics basis
This settings is then send as the `card:` common field.
None
Unit tests have been implemented to test the feature. QA has been done manually and can be found in https://github.com/DataDog/datadog-agent/pull/32917.
> Add Cardinality common field

- CHANGELOG.md
- datadog/dogstatsd/base.py
- tests/unit/dogstatsd/test_statsd.py
Fixes bug where `self._transport` was never set, thus causing `self._flush_telemetry` to fail when adding the `client_transport` tag.
Sets `self._transport` to `udp` as a default.
> Fix missing transport attribute when flushing telemetry
